---
# https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-create-first-template?tabs=azure-cli

- block:
  - include_role:
      name: azure/resource_group/create
      tasks_from: create

  - debug:
      var: az_resource_group
  - debug:
      var: key_vault
  - debug:
      var: app_service
  - debug:
      var: template_url
  - debug:
      var: parameter_url
  
  - debug:
      var: az_subscription_id
  - debug:
      var: az_service_principal_appid
  - debug:
      var: az_service_principal_password
  - debug:
      var: az_service_principal_tenant

  - fail:
      msg: break point


  - name: Create instance of Key Vault
    azure_rm_keyvault:
      resource_group: "{{az_resource_group}}"
      vault_name: samplekeyvault
      enabled_for_deployment: yes
      vault_tenant: 72f98888-8666-4144-9199-2d7cd0111111
      sku:
        name: standard
      access_policies:
      - tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
      object_id: 99998888-8666-4144-9199-2d7cd0111111
      keys:
      - get
      - list

  tags: [azure, az, deploy, key_vault, kv]
...