---
# https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-create-first-template?tabs=azure-cli


#   - include_role:
#       name: azure/key_vault/create
#       tasks_from: create

#   - debug:
#       var: key_vault
#   - debug:
#       var: service_plan
#   - debug:
#       var: az_appserviceplan_id

- block:
  - include_role:
      name: azure/resource_group/create
      tasks_from: create

  # https://docs.ansible.com/ansible/latest/modules/azure_rm_deployment_module.html
  - name: Deploy Azure Resource Manager Template
    azure_rm_deployment:
      name: "{{app_repo.arm_name | default(omit)}}"
      resource_group: "{{az_resource_group}}"
      location: "{{az_location}}"
      state: present
      template: "{{(app_repo.arm_template is defined) | ternary(lookup('file', app_repo.arm_template), omit)}}"
      template_link: "{{app_repo.arm_template_url | default(omit)}}"
      parameters: "{{app_repo.arm_parameters | default(omit)}}"
      parameters_link: "{{app_repo.arm_parameters_url | default(omit)}}"
  
  tags: [azure, az, deploy, resource_manager, arm]
...