---
# https://docs.ansible.com/ansible/latest/modules/azure_rm_appserviceplan_info_module.html
- name: Get facts for app service plan
  azure_rm_appserviceplan_info:
    resource_group:  "{{ resource_group }}"
    name:  "{{ service_plan }}"
  register: az_appserviceplan_facts

- debug:
    var: az_appserviceplan_id
...