---
- name: Display storage account name
  debug:
    var: az_plan

- name: Create storage account
  azure_rm_storageaccount:
    state: present
    name: "{{az_plan}}"
    resource_group: "{{az_group}}"
    account_type: "{{az_account_type}}"
