---
# https://docs.ansible.com/ansible/latest/modules/npm_module.html
# ansible linux -m include_role -a "name=linux/system/npm"

- name: Update the latest NPM packages globally
  npm:
    name: "{{item}}"
    global: true
    state: latest
  loop: "{{npm_packages}}"
  register: out_npm_latest
  tags: ["npm"]
...