---
# setup --skip-tags linux,az,config,choco,npm

# Ansible pip module does not work on Windows
- block:
  # https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
  - name: Upgrade pip (package manager)
    win_shell: python -m pip install --upgrade pip
    register: pip_manager_facts
    changed_when: "'Requirement already satisfied:' not in pip_manager_facts.stdout"

  - name: Upgrade pip package
    win_shell: "pip install --upgrade {{item}}"
    loop: "{{pip_packages}}"
    register: pip_package_facts
    changed_when: "'Requirement already satisfied:' not in pip_package_facts.stdout"

  # - name: Update pip package
  #   pip:
  #     name: "{{item}}"
  #     state: latest
  #   loop: "{{pip_packages}}"
  #   register: out_pip_latest

  tags: [pip]
...