---
# https://docs.ansible.com/ansible/latest/modules/azure_rm_resourcegroup_module.html
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{az_resource_group}}"
    location: "{{az_location}}"
  tags: [azure, az, app_service, publish, host]
...