services:
  pysubs2:
    build:
      context: .
      dockerfile: Dockerfile
    image: pysubs2-runner
    container_name: pysubs2-runner-container
    volumes:
      - /media/root/HDD-01:/mnt/hdd-01 # Mount media drives
      - /media/root/HDD-02:/mnt/hdd-02
      # Mount source files for live testing
      - ./:/app/dev
      # - ./convert-subtitles.py:/app/convert-subtitles-dev.py:ro
    stdin_open: true
    tty: true
    # The entrypoint will execute this command
    command: /bin/sh -l # Default to interactive shell


# :: Usage Example (run interactively) ::
# cd ~/Repos/pc-env/docker/pysubs2
# docker compose build --no-cache
# docker compose run --rm pysubs2
# --- Inside the container ---
# Check tool versions:
# mkvmerge --version
# ffmpeg -version
# subtitleedit --version
# tesseract --version
