---
# https://docs.ansible.com/ansible/latest/modules/azure_rm_sqlserver_facts_module.html
- name: List instances of SQL Server
  azure_rm_sqlserver_facts:
    resource_group: "{{ az_resource_group }}"

# - name: Get instance of SQL Server
#   azure_rm_sqlserver_facts:
#     resource_group: "{{ az_resource_group }}"
#     server_name: "{{ sql_server }}"
...