---
# Find with command: python3 -m site
python_user_base_dir: $HOME/.local
python_user_site_dir: "{{python_user_base_dir}}/lib/python3.6/site-packages"
python_user_command_dir: "{{python_user_base_dir}}/bin"

python_user_modules:
# --- Boilerplates ---
- boilerplates/logging_boilerplate.py
- boilerplates/shell_boilerplate.py
- boilerplates/git_boilerplate.py
- boilerplates/xml_boilerplate.py
- boilerplates/multiprocess_boilerplate.py
- boilerplates/daemon_boilerplate.py
- boilerplates/socket_boilerplate.py
# --- Misc. ---
- file_backup.py
- mytest.py
- test_process.py

python_user_commands:
- azure.py
...