---
# ansible localhost -m include_role -a "name=azure/sql_database/create"

- include_role:
    name: azure/sql_server/create

# https://docs.ansible.com/ansible/latest/modules/azure_rm_sqldatabase_module.html
- name: Create SQL database instance
  azure_rm_sqldatabase:
    name: "{{az_sql_database}}"
    resource_group: "{{az_resource_group}}"
    server_name: "{{az_sql_server}}"

# https://github.com/Azure-Samples/ansible-playbooks/blob/master/sql_create.yml
...