---
# https://docs.ansible.com/ansible/latest/modules/azure_rm_sqldatabase_facts_module.html
- name: List instances of SQL Database
  azure_rm_sqldatabase_facts:
    resource_group: "{{az_resource_group}}"
    server_name: "{{az_sql_server}}"

# - name: Get instance of SQL Database
#   azure_rm_sqldatabase_facts:
#     name: "{{az_sql_database}}"
#     resource_group: "{{az_resource_group}}"
#     server_name: "{{az_sql_server}}"
...