---
# This role is useful for creating a static app (client-side only)

# https://docs.ansible.com/ansible/latest/modules/azure_rm_storageaccount_module.html
- name: Create a storage account
  azure_rm_storageaccount:
    name: "{{ storage_account }}"
    resource_group: "{{ resource_group }}"
    account_type: Standard_LRS
    https_only: true
    kind: StorageV2
    state: present

# https://azure.microsoft.com/en-us/pricing/details/storage/
# - Standard_LRS
# - Standard_ZRS
# - Standard_GRS
# - Standard_RAGRS
# - StandardSSD_LRS
# - Premium_LRS
# - Premium_ZRS
...