---
# https://docs.microsoft.com/en-us/cli/azure/identity
# Configure default location:             az configure --defaults location=<location>
# Configure default resource group:       az configure --defaults group=<name>
# Configure default subscription:         az account set -s NAME_OR_ID

# az account list-locations

# https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli

# https://docs.microsoft.com/en-us/cli/azure/reference-index#az-configure
- block:
  - debug:
      msg: ewertz

  tags: [azure, az, active_directory, ad, account, configure]
...