---
# app_name: CloudShell
# app_name: DMR-2019-11-10--23-30
# app_name: RazorPagesMovie
app_name: ContosoUniversity

app_projects_tracked:
- DMR-VS
# - DMR-2019-11-09--15-42
- SexBound.WebApp

app_database_tools:
# https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp
- dotnet-ef                               # Install Entity Framework Core
# https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity
- dotnet-aspnet-codegenerator             # Install Code Generator (Scaffold)

# https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro#scaffold-student-pages
# The Microsoft.VisualStudio.Web.CodeGeneration.Design package is required for scaffolding.
# Although the app won't use SQL Server, the scaffolding tool needs the SQL Server package.
app_database_packages:
# Automatically includes Microsoft.EntityFrameworkCore as dependency
- Microsoft.EntityFrameworkCore.Sqlite    # Install SQLite database provider
- Microsoft.EntityFrameworkCore.SqlServer # Install SQL Server database provider
- Microsoft.EntityFrameworkCore.Design    # Install EF Core design package
- Microsoft.EntityFrameworkCore.Tools
- Microsoft.VisualStudio.Web.CodeGeneration.Design
- Microsoft.Extensions.Logging.Debug

app_use_extras: true
app_use_database: true
app_database_context: SchoolContext
app_authentication: None
# app_authentication: Individual
# app_authentication: MultiOrg

# app_location_dir: D:\Repos
app_location_dir: D:\Repos_Exp
app_project: "{{app_name}}.WebApp"

app_solution_dir: "{{app_location_dir}}\\{{app_name}}"
app_project_dir: "{{app_solution_dir}}\\{{app_project}}"
app_port: 43234
app_domain: "https://localhost:{{app_port}}"
app_sln: "{{app_solution_dir}}\\{{app_name}}.sln"
app_csproj: "{{app_project_dir}}\\{{app_project}}.csproj"
app_readme: "{{app_solution_dir}}\\README.md"
app_license: "{{app_solution_dir}}\\LICENSE"

app_repo_dir: "{{app_solution_dir}}\\.git"
app_gitignore: "{{app_solution_dir}}\\.gitignore"
app_gitattributes: "{{app_solution_dir}}\\.gitattributes"
...