---
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
# solution, source, host, projects (name, template, authentication)
# template choices: [console, xunit, webapp, webapi, sln]
# authentication choices: [None, Individual, MultiOrg]

# possible modes: [nodb, sqlserver, identity, docker]

app_projects:
- solution: DMR
  source: GitHub
  host: Azure
  projects:
  - name: DMR.WebApp
    template: webapp
    authentication: MultiOrg
  - name: DMR.UnitTests
    template: xunit

- solution: pc-setup
  source: GitHub

- solution: SexBound
  source: Azure
  host: Azure
  projects:
  - name: SexBound.WebApp
    template: webapp

- solution: CorruptionOfChampions
  source: Azure
  projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- solution: WorldOfWarcraftAddonDev
  source: Azure

- solution: Tutorials-WebApiApps
  source: GitHub
  projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: MultiOrg
  - name: WebApiApps.UnitTests
    template: xunit

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- solution: Tutorials-WebApps-RazorPages
  source: GitHub
  projects:
  - name: RazorPagesMovie
    template: webapp

- solution: Tutorials-DataAccess-RazorPages
  source: GitHub
  projects:
  - name: ContosoUniversity
    template: webapp

- solution: david-rachwalik.github.io
  source: GitHub
  host: GitHub
...