---
# --- Configuration Defaults ---
az_default_subscription: "{{az_subscriptions | first}}"
az_default_repository: "{{application_repositories | first}}"
az_default_location: southcentralus # South Central US     # az account list-locations
az_default_resource_group: Main
az_default_key_vault: main-keyvault
az_default_managed_identity: "{{az_managed_identities | first}}"
# --------------------------------------------------------
# --- Service Provider Index ---
# --------------------------------------------------------
# * List Azure AD service principal service providers
# az ad sp list --query "[].{Name:appDisplayName, Id:appId}" --output table --all
# az_ad_sp_service_providers: "{{az_ad_sp_list_facts.results | json_query('[*].stdout') | map('from_json') | list | items2dict}}"
az_ad_sp_service_providers: "{{az_ad_sp_list_facts.stdout | from_json | list | items2dict}}"
# * Fetch 'Microsoft Graph' service provider
# az ad sp list --query "[?appDisplayName=='Microsoft Graph'].appId | [0]" --all
#     "Microsoft Graph": "00000003-0000-0000-c000-000000000000"
# --------------------------------------------------------
# * List Azure AD service principal permissions
# az ad sp show --id "00000003-0000-0000-c000-000000000000" --query "appRoles[].{Value:value, Id:id}" --output table
# az_ad_sp_permissions: "{{az_ad_sp_permission_facts.results | json_query('[*].stdout') | map('from_json') | list | items2dict}}"
az_ad_sp_permissions: "{{az_ad_sp_permission_facts.stdout | from_json | list | items2dict}}"
# * Fetch 'User.Read' permission (Sign in and read user profile)
# az ad sp show --id "00000003-0000-0000-c000-000000000000" --query "oauth2Permissions[?value=='User.Read'].id | [0]"
#     "User.Read": "e1fe6dd8-ba31-4d61-89e7-88639da4683d"
# --------------------------------------------------------
# $openid = az ad sp show --id $graphId --query "oauth2Permissions[?value=='openid'].id | [0]"
# $profile = az ad sp show --id $graphId --query "oauth2Permissions[?value=='profile'].id | [0]"
# $userRead = az ad sp show --id $graphId --query "oauth2Permissions[?value=='User.Read'].id | [0]"
# $groupReadAll = az ad sp show --id $graphId --query "oauth2Permissions[?value=='Group.Read.All'].id | [0]"
# --------------------------------------------------------


# --- User (Signed-In) ---
az_user: "{{az_user_facts.stdout | from_json}}"
az_user_id: "{{az_user.objectId}}"


# --- Account Subscription (payment contract for resources) ---
az_subscription_item_query: "[?name=='{{az_default_subscription}}']"
az_subscription_item: "{{az_subscription_list_facts.stdout | from_json | json_query(az_subscription_item_query) | list | first}}"
az_tenant_id: "{{az_subscription_item.tenantId}}"
az_subscription_id: "{{az_subscription_item.id}}"
az_subscription: "{{az_subscription_item.name}}"
az_subscription_user: "{{az_subscription_item.user.name}}"


# --- Active Directory (tenant/directory to store resources) ---
az_ad_domain: "https://{{az_active_directory}}.onmicrosoft.com"
az_ad_identifier_urls: ["{{az_ad_domain}}/{{az_app_registration | lower}}"]
az_ad_reply_urls: ["{{app_domain}}/signin-oidc"]
az_devops_organization: "https://dev.azure.com/{{az_organization}}"


# --- Application Object Registration ---
# Products available by region: https://azure.microsoft.com/en-us/global-infrastructure/services
az_ad_app_project_query: "[?displayName=='{{az_app_registration}}'].{appId: appId, displayName: displayName}"
# http://jmespath.org/specification.html#contains
az_ad_app_project_delete_query: "[?displayName.contains(@, '{{az_ad_app_displayName_to_delete}}')].{appId: appId, displayName: displayName}"
az_ad_app_display_names: "{{ az_ad_app_list_facts.stdout | from_json | json_query('[*].displayName') | list | sort }}"
# https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade
az_ad_app_client_id: "{{az_ad_app_show_facts.stdout | default('{}', true) | from_json | json_query('appId')}}"
# System-Assigned Managed Identity: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview
# * App registration's ID (appId) is equal to service principal's objectId
az_ad_app_service_principal_id: "{{az_ad_app_sp_facts.stdout | default('{}', true) | from_json | json_query('appId')}}"
az_ad_sp_display_names: "{{ az_ad_app_list_facts.stdout | from_json | json_query('[*].displayName') | list | sort }}"
# --------------------------------------------------------
# --- Application Object Permissions ---
az_ad_app_permission_expected_ids: ["{{az_ad_sp_permissions['User.Read']}}"]
az_ad_app_permission_active_ids: "{{az_ad_app_permission_list_facts.stdout | from_json | json_query('[*].resourceAccess[*].id') | list | flatten}}"
az_ad_app_permission_missing_ids: "{{az_ad_app_permission_expected_ids | difference(az_ad_app_permission_active_ids)}}"


# --- User-Assigned Managed Identity ---
az_managed_identity_list_names: "{{az_managed_identity_list_facts.stdout | from_json | json_query('[*].name') | list}}"
az_managed_identity_list_to_delete: "{{az_managed_identity_list_names | difference(az_managed_identities)}}"

az_managed_identity_count: "{{az_managed_identity_list_names | count}}"
az_managed_identity_item_query: "[?name=='{{az_default_managed_identity}}']"
az_managed_identity_item: "{{az_managed_identity_list_facts.stdout | from_json | json_query(az_managed_identity_item_query) | list | first}}"

az_managed_identity_client_id: "{{az_managed_identity_item.clientId}}"
az_managed_identity_client_secret_url: "{{az_managed_identity_item.clientSecretUrl}}"
az_managed_identity: "{{az_managed_identity_item.name}}"
az_managed_identity_principal_id: "{{az_managed_identity_item.principalId}}"


# --- Service Principal / App Client Token ---
az_service_principal_list_names: "{{az_service_principal_facts.stdout | from_json | json_query('[*].appDisplayName') | list}}"
az_service_principal_list_apps: "{{az_service_principal_facts.stdout | from_json | json_query('[*].servicePrincipalType') | list}}"

az_service_principal_count: "{{az_service_principal_list_names | count}}"
az_service_principal_item_query: "[?name=='{{az_default_service_principal}}']"
az_service_principal_item: "{{az_service_principal_list_facts.stdout | from_json | json_query(az_service_principal_item_query) | list | first}}"
...