---
# --- Active Directory (tenant/directory to store resources) ---
az_active_directory: davidrachwalikoutlook
az_ad_domain: "https://{{az_active_directory}}.onmicrosoft.com"
az_ad_identifier_urls: ["{{az_ad_domain}}/{{app_project.name | lower}}"]
az_ad_reply_urls: ["{{app_domain}}/signin-oidc"]

# --- Configuration Defaults ---
az_default_subscription: "{{az_subscriptions | first}}"
az_default_location: South Central US
az_default_resource_group: Main
az_default_managed_identity: "{{az_managed_identities | first}}"

# --- Account Subscription (payment contract for resources) ---
az_subscriptions:
- Pay-As-You-Go
az_subscription_item_query: "[?name=='{{az_default_subscription}}']"
az_subscription_item: "{{az_subscription_list_facts.stdout | from_json | json_query(az_subscription_item_query) | list | first}}"
az_tenant_id: "{{az_subscription_item.tenantId}}"
az_subscription_id: "{{az_subscription_item.id}}"
az_subscription: "{{az_subscription_item.name}}"
az_subscription_user: "{{az_subscription_item.user.name}}"

# --- User-Assigned Managed Identity ---
az_managed_identities:
- MainDevelopment
# - MainStaging
- MainProduction
az_managed_identity_list_names: "{{az_managed_identity_list_facts.stdout | from_json | json_query('[*].name') | list}}"
az_managed_identity_list_to_delete: "{{az_managed_identity_list_names | difference(az_managed_identities)}}"

az_managed_identity_count: "{{az_managed_identity_list_names | count}}"
az_managed_identity_item_query: "[?name=='{{az_default_managed_identity}}']"
az_managed_identity_item: "{{az_managed_identity_list_facts.stdout | from_json | json_query(az_managed_identity_item_query) | list | first}}"

az_managed_identity_client_id: "{{az_managed_identity_item.clientId}}"
az_managed_identity_client_secret_url: "{{az_managed_identity_item.clientSecretUrl}}"
az_managed_identity: "{{az_managed_identity_item.name}}"
az_managed_identity_principal_id: "{{az_managed_identity_item.principalId}}"


# --- Service Principal / App Client Token ---
# az_service_principal: main-msi
az_service_principal: main-sp
az_service_principal_list_names: "{{az_service_principal_facts.stdout | from_json | json_query('[*].appDisplayName') | list}}"
az_service_principal_list_apps: "{{az_service_principal_facts.stdout | from_json | json_query('[*].servicePrincipalType') | list}}"

az_service_principal_count: "{{az_service_principal_list_names | count}}"
az_service_principal_item_query: "[?name=='{{az_default_service_principal}}']"
az_service_principal_item: "{{az_service_principal_list_facts.stdout | from_json | json_query(az_service_principal_item_query) | list | first}}"
...