---
# ansible home -m include_role -a "name=windows/backup/games/world_of_warcraft"

- name: Find World of Warcraft screenshots
  win_find:
    paths: "{{world_of_warcraft_backups | json_query('[*].screenshot_dir')}}"
  register: out_find_wow_ss
  ignore_errors: true

# - win_stat:
#     paths: "{{item.stat.path}}"
#   loop: "{{out_find_wow.results}}"

- name: Find World of Warcraft settings
  win_find:
    paths: "{{world_of_warcraft_backups | json_query('[*].wtf_dir')}}"
  register: out_find_wow_wtf

- name: Find World of Warcraft addons
  win_find:
    paths: "{{world_of_warcraft_backups | json_query('[*].addon_dir')}}"
  register: out_find_wow_mod
...