---
# ansible home -m include_role -a "name=windows/backup/games/world_of_warcraft"

- name: Find World of Warcraft screenshots
  win_find:
    paths: "{{world_of_warcraft_backups | json_query('[*].screenshot_dir')}}"
  register: out_find_wow_ss
  ignore_errors: true

# - win_stat:
#     paths: "{{item.stat.path}}"
#   loop: "{{out_find_wow.results}}"

- name: Find World of Warcraft settings
  win_find:
    paths: "{{world_of_warcraft_backups | json_query('[*].wtf_dir')}}"
  register: out_find_wow_wtf

- name: Find World of Warcraft addons
  win_find:
    paths: "{{world_of_warcraft_backups | json_query('[*].addon_dir')}}"
  register: out_find_wow_mod



# Taken from /home/rhodair/pc-setup/ansible_playbooks/roles/windows/backup/apps/vscode/tasks/main.yml

# ansible windows -m include_role -a 'name=windows/backup/apps/vscode'

# https://docs.ansible.com/ansible/latest/modules/win_file_module.html
# - name: Ensure backup directory exists
#   win_file:
#     path: D:\OneDrive\Backups\vscode-extensions
#     state: directory

# https://docs.ansible.com/ansible/latest/modules/win_copy_module.html
# - name: Backup World of Warcraft screenshots
#   win_copy:
#     # src: %USERPROFILE%\.vscode\extensions
#     src: C:\Users\david\.vscode\extensions
#     dest: D:\OneDrive\Backups\vscode-extensions
#     remote_src: true
#   loop: "{{world_of_warcraft_backups | json_query('[*].screenshot_dir')}}"
...