---
# ansible-playbook system_setup.yml --tags "apt"
# setup --tags apt --step

# https://stackoverflow.com/questions/41535838/how-to-run-apt-update-and-upgrade-via-ansible-shell

- block:
  # https://docs.ansible.com/ansible/latest/modules/include_role_module.html
  - include_role:
      name: linux/system/apt
      tasks_from: status
  
  # https://docs.ansible.com/ansible/latest/modules/apt_module.html
  - name: Upgrade distro packages
    apt:
      upgrade: dist
      force_apt_get: true

  # https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html
  - name: Add repository from PPA and install its signing key
    apt_repository:
      # https://git-scm.com/download/linux
      repo: ppa:git-core/ppa
      state: present

  - name: Install missing apt packages
    apt:
      name: "{{apt_packages_to_install}}"
      state: present

  - name: Upgrade all packages to the latest version
    apt:
      # name: "*"
      name: "{{apt_packages_installed}}"
      state: latest
      update_cache: yes
      # cache_valid_time: 3600 #One hour
      cache_valid_time: 86400 #One day
      force_apt_get: true

  - name: Remove useless packages from the cache
    apt:
      autoclean: true

  - name: Remove dependencies no longer required
    apt:
      autoremove: true

  tags: [apt]
...