---
# setup --skip-tags windows,az,config,pip

# https://help.ubuntu.com/community/AptGet/Howto
# https://stackoverflow.com/questions/41535838/how-to-run-apt-update-and-upgrade-via-ansible-shell
- block:
  # https://docs.ansible.com/ansible/latest/modules/include_role_module.html
  - include_role:
      name: linux/system/apt
      tasks_from: status
  
  # https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html
  - name: Add repository from PPA and install its signing key
    apt_repository:
      repo: "{{item}}"
      state: present
    loop: "{{apt_repository_packages}}"

  # https://docs.ansible.com/ansible/latest/modules/apt_module.html
  - name: Update apt repositories and cache
    apt:
      update_cache: true
      # force_apt_get: true
      cache_valid_time: 3600 #One hour
      # cache_valid_time: 86400 #One day

  - name: Upgrade all apt packages
    apt:
      upgrade: dist
      # force_apt_get: true

  - name: Install missing apt packages
    apt:
      name: "{{apt_packages_to_install}}"
      state: present
      # force_apt_get: true

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      # name: "{{apt_packages_installed}}"
      state: latest
      # force_apt_get: true
    ignore_errors: true

  - name: Remove useless packages from the cache
    apt:
      autoclean: true

  - name: Remove dependencies no longer required
    apt:
      autoremove: true

  tags: [linux, apt]
...