---
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# https://stackoverflow.com/questions/41535838/how-to-run-apt-update-and-upgrade-via-ansible-shell
# $ ansible localhost -m apt -a "upgrade=dist update_cache=yes cache_valid_time=86400" --become

- name: Upgrade all packages to latest version
  apt:
    # name: "*"
    upgrade: dist
    autoclean: yes
    autoremove: yes
    # cache_valid_time: 3600 #One hour
    cache_valid_time: 86400 #One day
    force_apt_get: true
    update_cache: yes
  register: out_apt_dist
  tags: ["apt"]

# TODO: query package list

# --- Only do this way if a package is missing ---
# - name: Update apt packages
#   apt:
#     # Provide loop directly into name
#     name: "{{apt_packages_diff}}"
#     state: latest
#     force_apt_get: true
#     autoclean: yes
#     autoremove: yes
#   register: out_apt_latest
#   tags: ["apt"]
...