---
# https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management

- block:
  - name: List installed VSCode extensions
    win_shell: "code --list-extensions"
    register: code_extension_facts
    changed_when: false
    no_log: true

  - set_fact:
      vscode_extensions_installed: "{{code_extension_facts.stdout_lines}}"

  - set_fact:
      vscode_extensions_to_install: "{{vscode_extensions | difference(vscode_extensions_installed)}}"

  tags: ["vscode"]


# - name: Install VSCode Extensions
#   win_command: "code --install-extension {{item}}"
#   loop: "{{vscode_extensions}}"


# Taken from /home/rhodair/pc-setup/ansible_playbooks/roles/windows/backup/apps/vscode/tasks/main.yml
# https://docs.ansible.com/ansible/latest/modules/win_file_module.html
# - name: Ensure backup directory exists
#   win_file:
#     path: D:\OneDrive\Backups\vscode-extensions
#     state: directory
# https://docs.ansible.com/ansible/latest/modules/win_copy_module.html
# - name: Backup VSCode Extensions
#   win_copy:
#     # src: %USERPROFILE%\.vscode\extensions
#     src: C:\Users\david\.vscode\extensions
#     dest: D:\OneDrive\Backups\vscode-extensions
#     remote_src: yes


# - name: Configure VSCode settings
#   - move json settings files for user and workspace


# TODO: https://docs.microsoft.com/en-us/visualstudio/online/quickstarts/vscode
...