---
- block:
  - name: Update shell aliases
    copy:
      src: "{{shell_alias | basename}}"
      dest: "{{shell_alias}}"
      mode: '0644'
    notify: source_shell_alias
    tags: ["alias"]

  - name: Verify script directory
    file:
      path: ~/bin
      state: directory
      mode: '0755'
    tags: ["bin"]

  # https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
  # https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-config

  # ----------------------------------------------------------------
  # https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
  # http://man.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/ssh-keygen.1?query=ssh-keygen%26sec=1
  # https://confluence.atlassian.com/bitbucketserver/creating-ssh-keys-776639788.html
  # --- Generate a new SSH key
  # ssh-keygen -b 4096 -t rsa -N '' -f '~/.ssh/id_rsa'
  # --- Assign it to the ssh-agent
  # ssh-add ~/.ssh/id_rsa
  # ----------------------------------------------------------------
  # https://stackoverflow.com/questions/34400272/visual-studio-code-always-asking-for-git-credentials
  # git config --get remote.origin.url
  # 	https://github.com/david-rachwalik/pc-setup.git
  # git remote set-url origin git@github.com:david-rachwalik/pc-setup.git
  # git push origin master:master
  # ----------------------------------------------------------------

  # - name: Set Git configuration user.name
  #   command: "git config --global user.name '{{username}}'"

  # - name: Set Git configuration user.email
  #   command: "git config --global user.email '{{ansible_user}}'"

  - name: Set Git configuration
    copy:
      src: .gitconfig
      dest: ~/.gitconfig


  tags: ["setup"]
...