---
# ansible-playbook system_setup.yml --tags logrotate

- block:
  - stat:
      path: /usr/bin/python
    register: python_command

  - name: Correct path to Python3
    file:
      src: /usr/bin/python3
      dest: /usr/bin/python
      state: link
    when: python_command.stat.exists == False

  tags: [python, py]


# https://docs.ansible.com/ansible/latest/modules/file_module.html
# Use case: Windows scheduled tasks (~/logs/ansible_win_backup.log)
- name: Ensure log directory exists
  file:
    path: "{{bash_log_dir}}"
    state: directory
    mode: 0775


# view /etc/logrotate.conf
# https://linux.die.net/man/8/logrotate
# https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04
- name: Update log rotate
  copy:
    src: "{{item}}"
    dest: "/etc/logrotate.d/{{item}}"
    mode: '0644'
  loop:
  - ansible_scheduled_task
  tags: [logrotate]
...