---
- block:
  - name: Update shell aliases
    copy:
      src: "{{shell_alias | basename}}"
      dest: "{{shell_alias}}"
      mode: '0644'
    notify: source_shell_alias
    tags: ["alias"]

  - name: Verify script directory
    file:
      path: ~/bin
      state: directory
      mode: '0755'
    tags: ["bin"]

  tags: ["setup", "scripts"]


- block:
  # https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
  # https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-config
  - name: Set Git configuration
    copy:
      src: "{{git_config | basename}}"
      dest: "{{git_config}}"
      mode: '0644'
    tags: ["config"]

  - name: Check Git repo for changes
    # command: "git status -uno"
    command: "git diff --name-only"
    args:
      chdir: "{{git_work_repo}}"
    register: out_git_status
    changed_when: false

  - set_fact:
      git_repo_changed_files: "{{out_git_status.stdout_lines}}"
  - set_fact:
      git_repo_is_safe: "{{git_repo_changed_files | count == 0}}"

  # https://docs.ansible.com/ansible/latest/modules/git_module.html
  - name: Pull the latest files from Git
    git:
      repo: "{{git_bare_repo}}"
      dest: "{{git_work_repo}}"
      # force: true
    when: git_repo_is_safe
    tags: ["pull"]
  
  tags: ["setup", "git"]
...