---
- name: Update shell aliases
  copy:
    src: "{{shell_alias | basename}}"
    dest: "{{shell_alias}}"
    mode: '0644'
  notify: source_shell_alias
  tags: ["setup", "alias"]

- name: Verify script directory
  file:
    path: ~/bin
    state: directory
    mode: '0755'
  tags: ["setup", "bin"]
...