---
# https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp

- name: List .NET Core tools installed
  win_shell: "dotnet tool list --global"
  loop: "{{app_database_tools}}"
  when: app_use_database
  register: out_tool_install
  changed_when: false
  tags: ["dotnet", "tool"]

# - name: Install .NET Core tool
#   win_shell: "dotnet tool install --global {{item}}"
#   loop: "{{app_database_tools}}"
#   when: app_use_database
#   register: out_tool_install
#   failed_when: not 'is already installed' in out_tool_install.stderr
#   changed_when: not 'is already installed' in out_tool_install.stderr

# - name: Ensure .NET Core tools are updated
#   win_shell: "dotnet tool update --global {{item}}"
#   loop: "{{app_database_tools}}"
#   when: app_use_database
#   register: out_tool_install
#   failed_when: not 'is already installed' in out_tool_install.stderr
#   changed_when: not 'is already installed' in out_tool_install.stderr
...