---
# https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator
# https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp
# ansible windows -m include_role -a name=windows/apps/dotnet/setup
# setup --tags dotnet


# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-list
- block:
  - name: List .NET Core tools installed
    win_shell: "dotnet tool list --global"
    # when: app_use_database
    register: out_tool_list
    changed_when: false # query only
    no_log: true

  - set_fact:
      dotnet_tools_installed: "{{out_tool_list.stdout | to_net_tools}}"

  - set_fact:
      dotnet_tools_to_install: "{{dotnet_tools_expected | difference(dotnet_tools_installed)}}"

  - name: Install .NET Core tool
    win_shell: >-
      dotnet tool install {{item}} --global
      --framework {{dotnet_default_framework}}
    loop: "{{dotnet_tools_to_install}}"
    # when: app_use_database
    register: out_tool_install
    changed_when: "'was successfully installed' in out_tool_install.stdout"

  - name: Update .NET Core tools
    win_shell: >-
      dotnet tool update {{item}} --global
      --framework {{dotnet_default_framework}}
    loop: "{{dotnet_tools_installed}}"
    # when: app_use_database
    register: out_tool_update
    changed_when: "'was successfully updated' in out_tool_update.stdout"

  tags: [dotnet, tool]
...