---
# https://samcogan.com/what-is-an-azure-app-service-plan-and-what-does-it-do/
# https://docs.microsoft.com/en-us/azure/app-service/overview-hosting-plans

- block:
  - include_role:
      name: azure/resource_group/create
      tasks_from: create

  - include_role:
      name: azure/service_plan/create
      tasks_from: status

  # https://docs.ansible.com/ansible/latest/modules/azure_rm_appserviceplan_module.html
  # Price Tiers:  F1, D1, B1, B2, B3, S1, P1, P1V2
  # https://azure.microsoft.com/en-us/pricing/details/app-service/linux/
  - name: Create app service plan
    azure_rm_appserviceplan:
      resource_group: "{{az_resource_group}}"
      name: "{{az_service_plan}}"
      is_linux: true
      sku: F1
      state: present
    when: az_service_plan_id is defined

  tags: [azure, az, app_service, publish, host]
...