---
# ansible-playbook app_create.yml -e "app_name=DMR"
# repoc -e "app_name=DMR"

- name: Create Azure Active Directory application
  hosts: localhost
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/include_role_module.html
  - include_role:
      name: azure/active_directory/create
    loop: "{{app_names}}"
    loop_control:
      loop_var: app_name
  tags: [azure, ad]


- name: Create .NET Core application repository
  hosts: windows
  tasks:
  - include_role:
      name: windows/apps/dotnet/new
    loop: "{{app_names}}"
    loop_control:
      loop_var: app_name
    tags: [new]
    
  - fail:
      msg: break point

  - include_role:
      name: windows/apps/git/init
    tags: [git]
    
  - include_role:
      name: windows/apps/dotnet/add
    tags: [add]
  
  tags: [dotnet]

  # - windows/apps/dotnet/ef
  # - { role: windows/apps/dotnet/build, app_open_vs: true }


# Modes: [nodb, sqlserver, docker] (when F1, ignore custom domain)

# https://docs.microsoft.com/en-us/azure/ansible/ansible-create-configure-azure-web-apps
# https://docs.microsoft.com/en-us/learn/paths/deploy-a-website-with-azure-app-service/
# https://www.youtube.com/playlist?list=PLdo4fOcmZ0oW8nviYduHq7bmKode-p8Wy
# https://docs.microsoft.com/en-us/azure/ansible/ansible-overview
# https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#azure

- name: Create Azure WebApp Service
  hosts: localhost
  vars:
    resource_group: DMR
  roles:
  - azure/app_service/create
  tags: [azure, ad]



# Modes: [blob, website] (when F1, ignore custom domain)

# https://docs.microsoft.com/en-us/azure/ansible/ansible-overview
# https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#azure

# https://www.youtube.com/watch?v=G_gDYlRBAZw
# https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website
# - name: Create Azure Static App Service (blog storage)
#   hosts: localhost
#   vars:
#     resource_group: StaticWebsite
#     storage_account: superfancysitename
#   roles:
#   - azure/storage_account/create
...