---
# ansible-playbook app_create.yml -e "app_repo_names=['DMR']"
# appc --tags ad -e "app_repo_names=['DMR']"
# appc --tags ad


- hosts: azure
  tasks:
  - name: Login Azure Active Directory subscription
    include_role:
      name: azure/active_directory/subscription
    tags: [azure, az, active_directory, ad, subscription, login]

  - name: Create Azure Active Directory application
    include_role:
      name: azure/active_directory/application/create
      tasks_from: loop_app_repo
    tags: [azure, az, active_directory, ad, application, identity]


- hosts: windows
  tasks:
  - name: Create .NET Core application repository
    include_role:
      name: windows/apps/dotnet/create
      tasks_from: loop_app_project
    tags: [repository, repo, dotnet, new, git]


- hosts: azure
  tasks:
  - name: Deploy Azure Resource Manager Template
    include_role:
      name: azure/resource_manager/deploy
      tasks_from: loop_app_repo
    tags: [azure, az, deploy, resource_manager, arm]

  - name: Deploy Azure Pipelines
    include_role:
      name: azure/pipelines/deploy
      tasks_from: loop_app_repo
    tags: [azure, az, deploy, pipelines]
...