---
# ansible-playbook app_create.yml -e "app_repo_names=['DMR']"
# appc -e "app_repo_names=['DMR']" --skip-tags "deploy"
# appc -e "app_repo_names=['DMR']" --skip-tags "ad,repo,arm"
# appc -e "app_repo_names=['DMR']" --skip-tags "ad,repo,pipelines"


- hosts: azure
  tasks:
  - name: Login Azure Active Directory subscription
    include_role:
      name: azure/active_directory/subscription
    tags: [azure, az, active_directory, ad, subscription, login]

  - name: Register Azure Active Directory application
    include_role:
      name: azure/active_directory/application/create
      tasks_from: loop_app_repo
    tags: [azure, az, active_directory, ad, application, identity]

  - name: Create .NET Core application
    include_role:
      name: linux/apps/dotnet/create
      tasks_from: loop_app_repo
    tags: [repository, repo, dotnet]

  - name: Initialize Git repository
    include_role:
      name: linux/apps/git/init
      tasks_from: loop_app_repo
    tags: [repository, repo, git]

  - name: Deploy Azure Resource Manager Template
    include_role:
      name: azure/resource_manager/deploy
      tasks_from: loop_app_repo
    tags: [azure, az, deploy, resource_manager, arm]

  - name: Deploy Azure Pipelines
    include_role:
      name: azure/pipelines/deploy
      tasks_from: loop_app_repo
    tags: [azure, az, deploy, pipelines]
...