---
# Use purge=True to remove [resource group, service plan]

- name: Delete Azure App Service
  hosts: localhost
  vars:
    resource_group_names:
    - ansible_test_rg
    - ansible_test_rg2nd
    - myTestPlan
    - myResourceGroupWebapp
    - myResourceGroup
  tasks:
  - name: Get facts for resource group
    azure_rm_resourcegroup_facts:
      name: "{{ item }}"
    loop: "{{ resource_group_names }}"
    register: az_resourcegroup_facts

  - name: Delete resource group
    azure_rm_resourcegroup:
      name: "{{ item.resourcegroups[0].name }}"
      state: absent
      force: true
    when: "{{ item | json_query('resourcegroups[*]') | list | count > 0 }}"
    loop: "{{ az_resourcegroup_facts.results }}"
...