---
- hosts: localhost
  # become: true
  # gather_facts: false
  environment: "{{azure_environment}}"
  # vars_files:
  # - group_vars/all/environment.yml
  # vars:
  #   ad_user: "{{vaulted_azure_environment.AZURE_AD_USER}}"
  #   password: "{{vaulted_azure_environment.AZURE_PASSWORD}}"
  #   subscription_id: "{{vaulted_azure_environment.AZURE_SUBSCRIPTION_ID}}"
  #   tenant: "{{vaulted_azure_environment.AZURE_TENANT}}"
  #   client_id: "{{vaulted_azure_environment.AZURE_CLIENT_ID}}"
  #   secret: "{{vaulted_azure_environment.AZURE_SECRET}}"
  tasks:
  - command: "printenv"
  
  # https://docs.ansible.com/ansible/latest/modules/azure_rm_resourcegroup_facts_module.html
  - name: Get facts for all resource groups
    azure_rm_resourcegroup_facts:

  # - name: Get facts for one resource group including resources it contains
  #   azure_rm_resourcegroup_facts:
  #     name: myResourceGroup
  #     list_resources: yes
...