---
# Modes: [blob, website] (when F1, ignore custom domain)

# https://docs.microsoft.com/en-us/azure/ansible/ansible-overview
# https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#azure

# https://www.youtube.com/watch?v=G_gDYlRBAZw
# https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website
- name: Create Azure App Service
  hosts: localhost
  vars:
    resource_group: StaticWebsite
    storage_account: superfancysitename
  roles:
  - azure/storage_account/create
...