---
# All Azure modules
# https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#azure

# - hosts: localhost
#   connection: local
#   gather_facts: false
#   vars:
#     app_name: "DavidRachwalik"
#   roles:
#     - az/resource_group
    # - az/web_app
    # - az/database
    # - az/identity


# https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html
# https://docs.ansible.com/ansible/latest/modules/azure_rm_deployment_module.html
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    app_name: "David_Rachwalik"
    template_url: "https://github.com/Rhodair/DevOps_AzureResourceGroup/blob/master/WebApp/WebSite.json"
    parameter_url: "https://github.com/Rhodair/DevOps_AzureResourceGroup/blob/master/WebApp/WebSite.parameters.json"
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: "{{app_name}}"
        template_link: "{{template_url}}"
        parameters_link: "{{parameter_url}}"
