---
# Modes: [nodb, sqlserver, identity, docker]
- name: Create a .NET Core project
  # Only for main PC
  hosts: home
  vars:
    app_project: DMR
    app_location: D:\Repos
    app_authentication: Individual
  roles:
  - windows/apps/dotnet/new
...