---
# Modes: [nodb, sqlserver, identity, docker]

- name: Create a .NET project
  hosts: localhost
  vars:
    resource_group: AngularWebApp
    app_path: ~/AngularWebApp
    app_service: WebApp
    # resource_group: DMR
  roles:
  - cross_platform/dotnet/new
  # - linux/web_project/create
  # - linux/web_project/database
  # - linux/web_project/identity
...