---
- name: Create a .NET Core application project
  hosts: localhost
  roles:
  - azure/active_directory/create


# Modes: [nodb, sqlserver, identity, docker]
- name: Create a .NET Core application project
  hosts: home
  roles:
  - windows/apps/dotnet/new
...