---
- name: Create .NET Core application project
  hosts: localhost
  roles:
  - name: azure/active_directory/create
    tags: [azure, ad]


- name: Create .NET Core application project
  hosts: windows
  roles:
  - name: windows/apps/dotnet/new
    tags: [dotnet, new]
  - name: windows/apps/git/init
    tags: [git]
  - name: windows/apps/dotnet/add
    tags: [dotnet, add]
  # - windows/apps/dotnet/ef
  # - { role: windows/apps/dotnet/build, app_open_vs: true }
...