---
- name: Create .NET Core application project
  hosts: localhost
  roles:
  - azure/active_directory/create


# Modes: [nodb, sqlserver, identity, docker]
- name: Create .NET Core application project
  hosts: home
  roles:
  - windows/apps/dotnet/new
  - windows/apps/git/init
  - windows/apps/dotnet/add
  # - windows/apps/dotnet/ef
  # - { role: windows/apps/dotnet/build, app_open_vs: true }
...