---
- name: Delete .NET Core application project
  hosts: localhost
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/include_role_module.html
  - include_role:
      name: azure/active_directory/delete
    tags: [azure, ad]


- name: Delete .NET Core application project
  # Only for main PC
  hosts: windows
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/win_stat_module.html
  - name: Obtain information about app project directory
    win_stat:
      path: "{{app_solution_dir}}"
    register: out_stat_app

  # https://docs.ansible.com/ansible/latest/modules/win_file_module.html
  - name: Purge directory
    win_file:
      name: "{{app_solution_dir}}"
      state: absent
    when: out_stat_app.stat.exists
...