---
# ansible-playbook secret_create.yml
# ansible-playbook secret_create.yml -e "kv_key=secret1 kv_value=test"
# secret -e "kv_key=secret1 kv_value=test"


- hosts: azure
  vars:
    az_resource_group: Main
    az_key_vault: main-keyvault
    az_client_id: "{{az_user_id}}"
  tasks:
  - name: Login Azure Active Directory subscription
    include_role:
      name: azure/active_directory/subscription
    tags: [azure, az, active_directory, ad, subscription, login]

  # not the same as managed user
  # - include_role:
  #     name: azure/active_directory/user
  #   tags: [azure, az, active_directory, ad, user]
  
  # create key vault to store service principals, passwords, connection strings, etc.
  # create credential file if missing

  - name: Create secret in Azure Key Vault
    include_role:
      name: azure/resources/key_vault/create
    tags: [azure, az, key_vault, kv, secret]

  # # https://docs.ansible.com/ansible/latest/modules/azure_rm_keyvault_info_module.html
  # - name: Get Key Vault by name
  #   azure_rm_keyvault_info:
  #     name: "{{az_default_key_vault}}"
  #     resource_group: "{{az_default_resource_group}}"
  #   register: key_vault_facts

  # # https://docs.ansible.com/ansible/latest/modules/azure_rm_keyvault_module.html
  # - name: Create instance of Key Vault
  #   azure_rm_keyvault:
  #     vault_name: "{{az_default_key_vault}}"
  #     resource_group: "{{az_default_resource_group}}"
  #     # Define false because default is null
  #     enabled_for_deployment: false
  #     enabled_for_disk_encryption: false
  #     enabled_for_template_deployment: true
  #     vault_tenant: "{{az_tenant_id}}"
  #     sku:
  #       name: standard
  #     access_policies:
  #     - tenant_id: "{{az_tenant_id}}"
  #       object_id: "{{az_default_user_id}}"
  #       certificates : [get, list, update, create, import, delete, recover, backup, restore, managecontacts, manageissuers, getissuers, listissuers, setissuers, deleteissuers]
  #       keys: [get, list, update, create, import, delete, recover, backup, restore]
  #   when: key_vault_facts.keyvaults | count == 0



# - name: Deploy secret to Azure Key Vault
#   hosts: azure
#   tasks:
#   - include_role:
#       name: azure/resource_manager/deploy
#       tasks_from: loop_app_repo
#   tags: [azure, az, deploy, resource_manager, arm]
...