---
- name: Backup important system files
  hosts: linux
  tasks:
  - include_role:
      name: linux/apps/backup
    loop: "{{app_ids}}"
    loop_control:
      loop_var: app_id
    tags: [app, backup, setting]

  - include_role:
      name: linux/games/backup
    loop: "{{game_ids}}"
    loop_control:
      loop_var: game_id
    tags: [game, backup, screenshot, ss, setting, addon]


- name: Clean system health
  hosts: windows
  become: true
  tasks:
  - include_role:
      name: windows/apps/ccleaner/clean
    tags: [ccleaner, clean]
  # - include_role:
  #     name: windows/apps/ccleaner/shutdown
  #   tags: [ccleaner, shutdown]
...