---
# This playbook will provision Windows 10

- hosts: windows
  become: true
  become_user: david
  become_method: runas
  roles:
  - windows/system/chocolatey/install
  - windows/system/chocolatey/uninstall
  # Install other software, such as scanner
  - windows/system/desktop/clean


  # https://docs.microsoft.com/en-us/powershell/windows/get-started?view=win10-ps
  # https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar
  # https://www.winsysadminblog.com/2019/03/change-windows-10-taskbar-icons-script-deploying-a-custom-taskbar-for-windows-10/
...