---
# This playbook's purpose is to provision WSL

- hosts: linux
  become: true
  roles:
  - linux/apt
  - linux/pip
  - linux/setup
  tasks:
  # https://docs.ansible.com/ansible/latest/modules/git_module.html
  - name: Pull the latest files from Git
    git:
      repo: "{{git_repo}}"
      dest: "{{wsl_repo}}"
      force: true
...