---
# This playbook's purpose is to provision Linux Ubuntu (WSL)

- hosts: linux
  become: true
  roles:
  - linux/apt
  - linux/pip


- hosts: linux
  roles:
  - linux/setup
  # - git/config
  # tasks:
  # # https://docs.ansible.com/ansible/latest/modules/git_module.html
  # - name: Pull the latest files from Git
  #   git:
  #     repo: "{{git_repo}}"
  #     dest: "{{wsl_repo}}"
  #     force: true

  # ansible-playbook wsl_update.yml --tags "vscode"
  # tasks:
  # - name: Install VSCode
  #   snap:
  #     name: code
  #     classic: true
  #   tags: ["vscode"]
...