---
# ansible localhost -m include_role -a "name=azure/web_app"

# https://docs.ansible.com/ansible/latest/modules/azure_rm_webapp_facts_module.html
- name: Get web app facts
  azure_rm_webapp_facts:
    resource_group: "{{ group_name }}"
    name: "{{ webapp_name }}"
  vars:
    webapp_name: DMR
  register: out_app_facts

- debug:
    var: out_app_facts


# - name: Create a windows web app
#   azure_rm_webapp:
#     state: present
#     name: "{{webapp_name}}"
#     resource_group: "{{az_group}}"
#     plan:
#       resource_group: "{{az_group}}"
#       name: "{{az_plan_name}}"
#       is_linux: false
#       sku: "{{az_plan_sku}}"

# - name: Create web application deployment
#   azure_rm_deployment:
#     state: present
#     name: "{{webapp_name}}"
#     resource_group: "{{az_group}}"
...