---
# setup --skip-tags linux,az,config,choco,pip

# https://docs.ansible.com/ansible/latest/modules/npm_module.html
- name: Update npm packages
  npm:
    name: "{{item}}"
    global: true
    state: latest
  loop: "{{npm_packages}}"
  register: out_npm_latest
  tags: [npm]
...