---
# setup --tags sh

- block:
  - name: Update bash shell aliases
    copy:
      src: "{{bash_user_alias | basename}}"
      dest: "{{bash_user_alias}}"
      mode: 0644

  tags: [bash, sh, alias]
...