---
- block:
  - name: Find Python site package directory
    command: python -m site --user-site
    register: py_user_site_results
    changed_when: false

  # https://docs.ansible.com/ansible/latest/modules/file_module.html
  - name: Ensure Python module directory exists
    file:
      path: "{{python_user_site_dir}}"
      state: directory
      mode: 0775

  # https://docs.ansible.com/ansible/latest/modules/copy_module.html
  - name: Deploy Python module
    copy:
      src: "{{item}}"
      dest: "{{python_user_site_dir}}/{{item | basename}}"
      mode: 0660
    loop: "{{python_user_modules}}"

  # - name: Install boilerplate package
  #   copy:
  #     src: /srv/myfiles/foo.conf
  #     dest: /etc/foo.conf
  #     mode: '0644'

  tags: [python, py]
...