---
# ansible-playbook app_create.yml --tags ad
# appc --tags ad

# managed identity:   Automatically rotates and manages service principals
# service principal:  Authentication token to access Azure resources

# https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli
# The key vault can exist in a different subscription than the resource group you're deploying to

# https://docs.microsoft.com/en-us/cli/azure/ad/sp
- block:
  - debug:
      msg: "Azure AD service principal: {{az_app_registration}}"


  - include_role:
      name: azure/active_directory/service_principal/show
  

  # --- Neither the create nor update action returns output ---
  # https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli
  - name: Create Azure AD service principal
    command: >-
      az ad sp create-for-rbac
      --name {{az_app_registration}}
      --create-cert
    # - store certificate in key vault
    when: az_ad_app_service_principal_id == ''
    # no_log: true

  - include_role:
      name: azure/active_directory/service_principal/show
    when: az_ad_app_service_principal_id == ''
  
  # --- Neither the create nor update action returns output ---
  # TODO: fix this step to accept changes *********************************
  - name: Update Azure AD service principal
    command: >-
      az ad sp update
      --id {{az_ad_app_service_principal_id}}
    # --set homepage={{app_domain}}
    # --set replyUrls={{az_ad_reply_urls}}
    # --set servicePrincipalNames={{az_ad_identifier_urls}}
    when: az_ad_app_service_principal_id != ''
    register: az_ad_sp_update_facts
    changed_when: az_ad_sp_update_facts.stdout != ''
    # no_log: true


  - name: List active AD service principals
    command: az ad sp list
    register: az_ad_sp_list_facts
    changed_when: false # query only
    no_log: true

  # - debug:
  #     var: az_ad_sp_display_names
  - debug:
      msg: "service principal count: {{az_ad_sp_display_names | count}}"

  tags: [azure, az, active_directory, ad, application, identity, service_principal, sp]
...