---
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
# Application Repository Options:   [solution, source, host, projects]
# Application Project Options:      [name, template, authentication, port]
# - template choices:               [webapp, webapi, xunit, console]
# - authentication choices:         [Individual, SingleOrg]

# possible modes: [nodb, sqlserver, identity, docker]

# app_repo_name = app_repositories[*].solution
app_repositories:
- solution: pc-setup
  source: GitHub

- solution: DMR
  source: GitHub
  host: Azure
  projects:
  - name: DMR.WebApp
    template: webapp
    authentication: SingleOrg
  - name: DMR.UnitTests
    template: xunit

- solution: SexBound
  source: Azure
  host: Azure
  projects:
  - name: SexBound.WebApp
    template: webapp

- solution: CorruptionOfChampions
  source: Azure
  projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- solution: WorldOfWarcraftAddonDev
  source: Azure

- solution: Tutorials-WebApiApps
  source: GitHub
  projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: SingleOrg
  - name: WebApiApps.UnitTests
    template: xunit

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- solution: Tutorials-WebApps-RazorPages
  source: GitHub
  projects:
  - name: RazorPagesMovie
    template: webapp

- solution: Tutorials-DataAccess-RazorPages
  source: GitHub
  projects:
  - name: ContosoUniversity
    template: webapp

# https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index

- solution: david-rachwalik.github.io
  source: GitHub
  host: GitHub

- solution: Tester
  source: GitHub
  host: Azure
  projects:
  - name: Tester.Api
    template: webapi
    authentication: SingleOrg
  # - name: Tester.WebApp
  #   template: webapp
  #   authentication: SingleOrg
  # - name: Tester.UnitTests
  #   template: xunit
  use_extras: true


# ------------------------ Application Repository/Project Parsing ------------------------

# Application repository/project names must be unique
app_repo_names: "{{app_repositories | json_query('[*].solution')}}"
app_project_names: "{{app_repo | json_query('projects[*].name')}}"

app_repo_query: "[?solution=='{{app_repo_name}}']"
app_project_query: "[*].projects[?name=='{{app_project_name}}']"

app_repo: "{{app_repositories | json_query(app_repo_query) | first}}"
app_project: "{{app_repositories | json_query(app_project_query) | flatten | first}}"


app_authentication: "{{app_project.authentication | default('None')}}"
app_domain: "https://localhost:{{app_project.port | default(5001)}}"
app_use_extras: "{{app_repo.use_extras | default(false)}}"
# app_use_database: "{{app_project.use_database | default(false)}}"
# app_database_context: MainContext
...