---
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
# Application Repository Options:   [solution, source, host, projects]
# Application Project Options:      [name, template, authentication, port]
# - template choices:               [webapp, webapi, xunit, console]
# - authentication choices:         [Individual, SingleOrg]

# possible modes: [nodb, sqlserver, identity, docker]

# app_repo_name = app_repositories[*].solution
app_repositories:
- solution: pc-setup
  source: GitHub

- solution: DMR
  source: GitHub
  host: Azure
  projects:
  - name: DMR.WebApp
    template: webapp
    authentication: SingleOrg
  - name: DMR.UnitTests
    template: xunit

- solution: SexBound
  source: Azure
  host: Azure
  projects:
  - name: SexBound.WebApp
    template: webapp

- solution: CorruptionOfChampions
  source: Azure
  projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- solution: WorldOfWarcraftAddonDev
  source: Azure

- solution: Tutorials-WebApiApps
  source: GitHub
  projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: SingleOrg
  - name: WebApiApps.UnitTests
    template: xunit

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- solution: Tutorials-WebApps-RazorPages
  source: GitHub
  projects:
  - name: RazorPagesMovie
    template: webapp

- solution: Tutorials-DataAccess-RazorPages
  source: GitHub
  projects:
  - name: ContosoUniversity
    template: webapp

# https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index

- solution: david-rachwalik.github.io
  source: GitHub
  host: GitHub

- solution: Tester
  source: GitHub
  host: Azure
  projects:
  - name: Tester.Api
    template: webapi
    authentication: SingleOrg
  
  # arm_template_url: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-web-app-github-deploy/azuredeploy.json
  arm_template: "201-web-app-github-deploy/azuredeploy.json"
  arm_parameters:
    location:
      value: "South Central US"
    # siteName:
    #   # value: "Tester"
    #   # value: "GEN-UNIQUE"
    #   value: "{{az_app_service}}"

  # template_url: "https://github.com/Rhodair/DevOps_AzureResourceGroup/blob/master/WebApp/WebSite.json"
  # parameter_url: "https://github.com/Rhodair/DevOps_AzureResourceGroup/blob/master/WebApp/WebSite.parameters.json"

  # template_url: blank.json
  # parameter_url: blank.parameters.dev.json

  # template_url: https://raw.githubusercontent.com/david-rachwalik/pc-setup/master/ansible_playbooks/roles/azure/resource_manager/files/blank.json
  # parameter_url: https://raw.githubusercontent.com/david-rachwalik/pc-setup/master/ansible_playbooks/roles/azure/resource_manager/files/blank.parameters.dev.json

  # template_url: https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.json
  # parameter_url: https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.parameters.json

  # template_url: 201-web-app-github-deploy/azuredeploy.json
  # parameters: 201-web-app-github-deploy/azuredeploy.parameters.json

  # - name: Tester.WebApp
  #   template: webapp
  #   authentication: SingleOrg
  # - name: Tester.UnitTests
  #   template: xunit
  use_extras: true


# ------------------------ Application Repository/Project Parsing ------------------------

# Application repository/project names must be unique
app_repo_names: "{{app_repositories | json_query('[*].solution')}}"
app_project_names: "{{app_repo | json_query('projects[*].name')}}"

app_repo_query: "[?solution=='{{app_repo_name}}']"
app_project_query: "[*].projects[?name=='{{app_project_name}}']"

app_repo: "{{app_repositories | json_query(app_repo_query) | first}}"
app_project: "{{app_repositories | json_query(app_project_query) | flatten | first}}"
...