---
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
# Application Repository Options:   [solution, source, host, projects]
# Application Project Options:      [name, template, authentication, port]
# - template choices:               [webapp, webapi, xunit, console]
# - authentication choices:         [Individual, SingleOrg, MultiOrg]
# * always prefer MultiOrg for most and SingleOrg for APIs

# possible modes: [nodb, sqlserver, identity, docker]

# app_repo_name = app_repositories[*].solution
app_repositories:
- solution: pc-setup
  source: GitHub

- solution: DMR
  source: GitHub
  host: Azure
  projects:
  - name: DMR.WebApp
    template: webapp
    authentication: MultiOrg
  - name: DMR.UnitTests
    template: xunit

- solution: SexBound
  source: Azure
  host: Azure
  projects:
  - name: SexBound.WebApp
    template: webapp

- solution: CorruptionOfChampions
  source: Azure
  projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- solution: WorldOfWarcraftAddonDev
  source: Azure

- solution: Tutorials-WebApiApps
  source: GitHub
  projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: SingleOrg
  - name: WebApiApps.UnitTests
    template: xunit

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- solution: Tutorials-WebApps-RazorPages
  source: GitHub
  projects:
  - name: RazorPagesMovie
    template: webapp

- solution: Tutorials-DataAccess-RazorPages
  source: GitHub
  projects:
  - name: ContosoUniversity
    template: webapp

# https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index

- solution: david-rachwalik.github.io
  source: GitHub
  host: GitHub

- solution: Tester
  source: GitHub
  host: Azure
  projects:
  - name: Tester.Api
    template: webapi
    authentication: SingleOrg
  
  # arm_template: 201-web-app-github-deploy/azuredeploy.json
  # arm_parameters: 201-web-app-github-deploy/azuredeploy.parameters.json
  
  arm_template: linux/webapp_blank/azuredeploy.json
  arm_parameters: linux/webapp_blank/azuredeploy.parameters.json

  # arm_template_url: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-web-app-github-deploy/azuredeploy.json

  # template_url: https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.json
  # parameter_url: https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.parameters.json

  # - name: Tester.WebApp
  #   template: webapp
  #   authentication: MultiOrg
  # - name: Tester.UnitTests
  #   template: xunit
  use_extras: true

- solution: Main
  host: Azure
  arm_template: all/managed_identity/azuredeploy.json
  arm_parameters: all/managed_identity/azuredeploy.parameters.json

- solution: WebAppTest
  host: Azure
  arm_template: all/webapp_sql/azuredeploy.json
  arm_parameters: all/webapp_sql/azuredeploy.parameters.json
  arm_parameter_inputs:
  - name: sql_administrator_login
    prompt: "What is the database administrator username?"
  - name: sql_administrator_login_password
    prompt: "What is the database administrator password?"


# ------------------------ Application Repository/Project Parsing ------------------------

# Application repository/project names must be unique
app_repo_names: "{{app_repositories | json_query('[*].solution')}}"
app_project_names: "{{app_repo | json_query('projects[*].name')}}"

app_repo_query: "[?solution=='{{app_repo_name}}']"
app_repo: "{{app_repositories | json_query(app_repo_query) | first}}"

app_project_query: "[*].projects[?name=='{{app_project_name}}']"
app_project: "{{app_repositories | json_query(app_project_query) | flatten | first}}"
...