---
# -------- Application Repository Options --------
# --- requires 'dotnet_projects' to create solution directory ---
# ------------------------------------------------
# name:                   repository directory, dotnet solution
# source:                 [github, tfsgit]
# dotnet_projects:        list of .NET project configurations
# -------- ASP.NET Core Project Options --------
# name:                   dotnet project name within solution
# template:               [webapp, webapi, xunit, console]
# database_context:       DbContext to generate; activates SQL database
# authentication:         [Individual, SingleOrg, MultiOrg]
# -------- Host Options --------
# az_resource_manager:    relative path to Azure Resource Manager (ARM) template
# az_pipeline:            path to Azure Pipelines file
# ------------------------------------------------

# .NET project 'name':
# - *.WebApp              triggers pipeline task Deploy App Service 
# - *.UnitTests           triggers pipeline task Run Tests
# - *.SQL                 triggers pipeline task Deploy SQL Database
# - *.API                 triggers pipeline task Deploy App Service

# .NET project 'authentication' is typically MultiOrg (SingleOrg for APIs)
# ARM template mode plans: [nodb, sqlserver, identity, docker]


# Development, Staging Area, Production
# - using abbreviations to allow more namespace for resources
application_environment_choices: [Dev, SA, Prod]
application_authentication_choices: [Individual, SingleOrg, MultiOrg]

# app_repo = application_repositories[*].name
application_repositories:
# --- Primary Repositories ---

- name: pc-setup
  source: github

- name: DMR
  source: github
  dotnet_projects:
  - name: DMR.WebApp
    template: webapp
    # database_context: MainContext
    # authentication: MultiOrg
    # az_pipelines: true
    # az_resource_manager: all/webapp_sql
    # az_resource_manager: linux/webapp_blank
  # - name: DMR.UnitTests
  #   template: xunit
  # - name: DMR.API
  #   template: webapi
  #   authentication: SingleOrg
  az_environments: [Dev]
  # az_resource_manager: all/webapp_sql
  az_resource_manager: linux/webapp_blank
  az_pipelines: linux/basic

- name: david-rachwalik.github.io
  source: github


# --- Test Repositories ---

- name: Test-Basic
  source: github
  dotnet_projects:
  - name: Test-Basic.WebApp
    template: webapp
    database_context: MainContext
    authentication: MultiOrg
  # - name: Test-Basic.UnitTests
  #   template: xunit
  az_resource_manager: linux/webapp_blank
  az_pipelines: true

- name: Test-Database
  source: github
  dotnet_projects:
  - name: Test-Database.WebApp
    template: webapp
    database_context: MainContext
  az_resource_manager: all/webapp_sql
  az_pipelines: true

- name: Test-Identity
  source: github
  dotnet_projects:
  - name: Test-Identity.WebApp
    template: webapp
    database_context: MainContext
    authentication: MultiOrg
  az_resource_manager: all/webapp_sql
  az_pipelines: true


# --- Tutorial Repositories ---

- name: Tutorials-WebApiApps
  source: github
  dotnet_projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: MultiOrg

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- name: Tutorials-WebApps-RazorPages
  source: github
  dotnet_projects:
  - name: RazorPagesMovie
    template: webapp

- name: Tutorials-DataAccess-RazorPages
  source: github
  dotnet_projects:
  - name: ContosoUniversity
    template: webapp


# --- Backup Repositories ---

- name: SexBound
  source: tfsgit # Azure
  dotnet_projects:
  - name: SexBound.WebApp
    template: webapp
  # az_resource_manager: all/webapp_sql

- name: CorruptionOfChampions
  source: tfsgit # Azure
  dotnet_projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- name: WorldOfWarcraftAddonDev
  source: tfsgit # Azure


# ------------------------ Application Repository/Project Parsing ------------------------

# Application repository/project names must be unique
app_repo_names: "{{application_repositories | json_query('[*].name')}}"
app_project_names: "{{app_repo_item | json_query('dotnet_projects[*].name')}}"

app_repo_query: "[?name=='{{app_repo}}']"
app_repo_item: "{{application_repositories | json_query(app_repo_query) | first}}"

app_project_query: "[*].dotnet_projects[?name=='{{app_project}}']"
app_project_item: "{{application_repositories | json_query(app_project_query) | flatten | first}}"

# --- Configuration Defaults ---
app_environments: "{{app_repo_item.az_environments | default(application_environment_choices)}}"
app_environment: "{{app_environments | first}}"
app_domain: "https://localhost:5001"
app_database_context: "{{app_project_item.database_context | default('None')}}"
app_authentication: "{{app_project_item.authentication | default('None')}}"
...