---
# -------- Application Repository Options --------
# --- requires 'dotnet_projects' to create solution directory ---
# ------------------------------------------------
# name:               repository directory, solution
# source:             [GitHub, Azure]
# dotnet_projects:    list of .NET project configurations
# -------- ASP.NET Core Project Options --------
# name:               dotnet project name within solution
# template:           [webapp, webapi, xunit, console]
# sql_database:       false by default, automatically true with authentication
# authentication:     [Individual, SingleOrg, MultiOrg]
# -------- Host Options --------
# az_rm_template:     path to Azure Resource Manager (ARM) template file
# az_rm_parameters:   path to Azure Resource Manager (ARM) parameter file
# az_pipeline:        path to Azure Pipelines file
# ------------------------------------------------

# .NET project 'name':
# - *.WebApp          triggers pipeline task Deploy App Service 
# - *.UnitTests       triggers pipeline task Run Tests
# - *.API             triggers pipeline task Deploy SQL Database

# .NET project 'authentication' is typically MultiOrg (SingleOrg for APIs)
# ARM template mode plans: [nodb, sqlserver, identity, docker]


# Development, Staging Area, Production
# - using abbreviations to allow more namespace for resources
application_environment_choices: [Dev, SA, Prod]
application_authentication_choices: [Individual, SingleOrg, MultiOrg]

# app_repo = application_repositories[*].name
application_repositories:
- name: Tester
  source: GitHub
  dotnet_projects:
  - name: Tester.WebApp
    template: webapp
    database_context: MainContext
    authentication: MultiOrg
    az_pipelines: true
  # - name: Tester.UnitTests
  #   template: xunit
  # - name: Tester.API
  #   template: webapi
  #   authentication: SingleOrg
  # az_rm_template: all/webapp_sql/azuredeploy.json
  # az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json

- name: pc-setup
  source: GitHub

- name: DMR
  source: GitHub
  dotnet_projects:
  - name: DMR.WebApp
    template: webapp
    database_context: MainContext
    authentication: MultiOrg
    az_pipelines: true
    az_resource_manager: all/webapp_sql
  - name: DMR.UnitTests
    template: xunit
  # az_rm_template: all/webapp_sql/azuredeploy.json
  # az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json

- name: SexBound
  source: Azure
  dotnet_projects:
  - name: SexBound.WebApp
    template: webapp
  # az_rm_template: all/webapp_sql/azuredeploy.json
  # az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json

- name: CorruptionOfChampions
  source: Azure
  dotnet_projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- name: WorldOfWarcraftAddonDev
  source: Azure

- name: Tutorials-WebApiApps
  source: GitHub
  dotnet_projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: MultiOrg
  - name: WebApiApps.UnitTests
    template: xunit

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- name: Tutorials-WebApps-RazorPages
  source: GitHub
  dotnet_projects:
  - name: RazorPagesMovie
    template: webapp

- name: Tutorials-DataAccess-RazorPages
  source: GitHub
  dotnet_projects:
  - name: ContosoUniversity
    template: webapp

- name: david-rachwalik.github.io
  source: GitHub


# ------------------------ Application Repository/Project Parsing ------------------------

# Application repository/project names must be unique
app_repo_names: "{{application_repositories | json_query('[*].name')}}"
app_project_names: "{{app_repo_item | json_query('dotnet_projects[*].name')}}"

app_repo_query: "[?name=='{{app_repo}}']"
app_repo_item: "{{application_repositories | json_query(app_repo_query) | first}}"

app_project_query: "[*].dotnet_projects[?name=='{{app_project}}']"
app_project_item: "{{application_repositories | json_query(app_project_query) | flatten | first}}"

# --- Configuration Defaults ---
app_environments: "{{app_repo_item.az_environments | default(application_environment_choices)}}"
app_environment: "{{app_environments | first}}"
app_domain: "https://localhost:5001"
app_authentication: "{{app_project_item.authentication | default('None')}}"
app_database_context: "{{app_project_item.database_context | default('None')}}"
...