---
# -------- Application Repository Options --------
# --- requires 'dotnet_projects' to create solution directory ---
# ------------------------------------------------
# name:               repository directory, solution
# source:             [GitHub, Azure]
# dotnet_projects:    list of .NET project configurations
# -------- ASP.NET Core Project Options --------
# name:               dotnet project name within solution
# template:           [webapp, webapi, xunit, console]
# authentication:     [Individual, SingleOrg, MultiOrg]
# port:               5001 default
# -------- Host Options --------
# az_rm_template:     path to Azure Resource Manager (ARM) template file
# az_rm_parameters:   path to Azure Resource Manager (ARM) parameter file
# az_pipeline:        path to Azure Pipelines file

# * authentication typically MultiOrg (SingleOrg for APIs)
# * ARM template modes: [nodb, sqlserver, identity, docker]


application_environments: [Development, Staging, Production]

# app_repo = application_repositories[*].name
application_repositories:
# - name: Main
#   host: Azure
#   azure_devops_projects:
#   - host: Azure
#   # az_rm_template: all/managed_identity/azuredeploy.json
#   # az_rm_parameters: all/managed_identity/azuredeploy.parameters.json

- name: pc-setup
  source: GitHub

- name: DMR
  source: GitHub
  dotnet_projects:
  - name: DMR.WebApp
    template: webapp
    authentication: MultiOrg
  - name: DMR.UnitTests
    template: xunit
  # az_rm_template: all/webapp_sql/azuredeploy.json
  # az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json

- name: SexBound
  source: Azure
  dotnet_projects:
  - name: SexBound.WebApp
    template: webapp
  # az_rm_template: all/webapp_sql/azuredeploy.json
  # az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json

- name: CorruptionOfChampions
  source: Azure
  dotnet_projects:
  - name: CorruptionOfChampions.Conversion
    template: webapp
  - name: CorruptionOfChampions.WebApp
    template: webapp

- name: WorldOfWarcraftAddonDev
  source: Azure

- name: Tutorials-WebApiApps
  source: GitHub
  dotnet_projects:
  - name: WebApiApps.WebApp
    template: webapp
    authentication: SingleOrg
  - name: WebApiApps.UnitTests
    template: xunit

# https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages
- name: Tutorials-WebApps-RazorPages
  source: GitHub
  dotnet_projects:
  - name: RazorPagesMovie
    template: webapp

- name: Tutorials-DataAccess-RazorPages
  source: GitHub
  dotnet_projects:
  - name: ContosoUniversity
    template: webapp

# https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index

- name: david-rachwalik.github.io
  source: GitHub

- name: Tester
  source: GitHub
  dotnet_projects:
  - name: Tester.Api
    template: webapi
    authentication: SingleOrg
  # az_rm_template: all/webapp_sql/azuredeploy.json
  # az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json
  
  # az_rm_template: 201-web-app-github-deploy/azuredeploy.json
  # az_rm_parameters: 201-web-app-github-deploy/azuredeploy.parameters.json
  
  az_rm_template: linux/webapp_blank/azuredeploy.json
  az_rm_parameters: linux/webapp_blank/azuredeploy.parameters.json

  # arm_template_url: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-web-app-github-deploy/azuredeploy.json

  # template_url: https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.json
  # parameter_url: https://github.com/Azure/azure-quickstart-templates/blob/master/201-web-app-github-deploy/azuredeploy.parameters.json

  # - name: Tester.WebApp
  #   template: webapp
  #   authentication: MultiOrg
  # - name: Tester.UnitTests
  #   template: xunit
  use_extras: true

- name: WebAppTest
  az_rm_template: all/webapp_sql/azuredeploy.json
  az_rm_parameters: all/webapp_sql/azuredeploy.parameters.json


# ------------------------ Application Repository/Project Parsing ------------------------

# Application repository/project names must be unique
app_repo_names: "{{application_repositories | json_query('[*].name')}}"
app_project_names: "{{app_repo_item | json_query('dotnet_projects[*].name')}}"

app_repo_query: "[?name=='{{app_repo}}']"
app_repo_item: "{{application_repositories | json_query(app_repo_query) | first}}"

app_project_query: "[*].dotnet_projects[?name=='{{app_project}}']"
app_project_item: "{{application_repositories | json_query(app_project_query) | flatten | first}}"
...