---
# Products available by region
# https://azure.microsoft.com/en-us/global-infrastructure/services/

az_active_directory: davidrachwalikoutlook
az_ad_domain: "https://{{az_active_directory}}.onmicrosoft.com"
az_ad_identifier_urls: ["{{az_ad_domain}}/{{app_project.name | lower}}"]
az_ad_reply_urls: ["{{app_domain}}/signin-oidc"]

# az_ad_app_project_query: "[?displayName=='{{app_project.name}}']"
az_ad_app_project_query: "[?displayName=='{{app_project.name}}'].{appId: appId, displayName: displayName}"
# http://jmespath.org/specification.html#contains
az_ad_app_project_delete_query: "[?displayName.contains(@, '{{az_ad_app_displayName_to_delete}}')].{appId: appId, displayName: displayName}"

# https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade
az_ad_app_show_parse: "{{ out_ad_app_show.stdout | from_json }}"
# az_ad_app_keys: "{{(out_ad_app_create.stdout | from_json).keys() | list | sort}}"
# az_ad_app_convert: "{{out_ad_app_create.stdout | from_json | json_query('{appId: appId, displayName: displayName}')}}"
az_ad_app_project_id: "{{out_ad_app_show.stdout | from_json | json_query('appId')}}"


# ------------------------------------------------
# https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions
az_project: "{{app_repo.solution | lower}}"
az_location: "{{app_repo.arm_location | default('South Central US')}}"
az_resource_group: "{{az_project}}-rg"

az_rm_template: "{{ lookup('template', app_repo.arm_template) }}"
az_rm_parameters_file: "{{ lookup('template', app_repo.arm_parameters) }}"
az_rm_parameters: "{{ (az_rm_parameters_file is defined) | ternary(az_rm_parameters_file.parameters, {}) }}"

# 'az_plan' must be between 3-24 chars, only lowercase or numbers
# TODO: replace() will use regex to strip ALL special characters
# az_service_plan: "plan-{{app_project.name | replace('_', '') | truncate(19) | lower}}"
# app must be globally unique with valid characters a-z, 0-9, and -
az_service_plan: "{{az_project}}-plan"
az_service_plan_id: "{{az_appserviceplan_facts | json_query('appserviceplans[0].id')}}"
az_app_service: "{{az_project}}-app"
# sql_server name must contain only lowercase letters, numbers, and hyphens; must be 3-50 characters long
az_sql_server: "{{az_project}}-sql"
az_sql_database: "{{az_project}}-sqldb"
az_storage_account: "{{az_project}}-sa"
# database username must be unique within Azure; must not contain the '@' symbol for local Git pushes
# database password must contain at least 2 of the 3 elements: letters, numbers, and symbols; must be >= 8 characters long

app_authentication: "{{app_project.authentication | default('None')}}"
app_domain: "https://localhost:{{app_project.port | default(5001)}}"
app_use_extras: "{{app_repo.use_extras | default(false)}}"
# app_use_database: "{{app_project.use_database | default(false)}}"
# app_database_context: MainContext
...