---
dotnet_default_framework: net5.0 # netcoreapp3.1

dotnet_tools_expected:
# https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp
- dotnet-ef                                 # Install Entity Framework Core
# https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity
- dotnet-aspnet-codegenerator               # Install Code Generator (Scaffold)


# https://www.nuget.org/packages/*
dotnet_development_packages:
- Microsoft.VisualStudio.Web.BrowserLink
- Microsoft.CodeAnalysis.FxCopAnalyzers

# https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro#scaffold-student-pages
# The Microsoft.VisualStudio.Web.CodeGeneration.Design package is required for scaffolding.
# Although the app won't use SQL Server, the scaffolding tool needs the SQL Server package.
dotnet_database_packages:
# Automatically includes Microsoft.EntityFrameworkCore as dependency
# - Microsoft.EntityFrameworkCore.Sqlite      # Install SQLite database provider
- Microsoft.EntityFrameworkCore.SqlServer   # Install SQL Server database provider
- Microsoft.EntityFrameworkCore.Design      # Install EF Core design package
- Microsoft.EntityFrameworkCore.Tools
- Microsoft.VisualStudio.Web.CodeGeneration.Design
- Microsoft.Extensions.Logging.Debug

dotnet_identity_packages:
- Microsoft.AspNetCore.Authentication.AzureAD.UI
# Install-Package Microsoft.Owin.Security.OpenIdConnect
# Install-Package Microsoft.Owin.Security.Cookies
# Install-Package Microsoft.Owin.Host.SystemWeb

dotnet_packages: "{{dotnet_development_packages | union(dotnet_database_packages) | union(dotnet_identity_packages)}}"
...