---
# ansible-playbook app_create.yml --tags deploy -e "app_repo_names=['DMR']"
# appc --tags deploy -e "app_repo_names=['DMR']"
# appc --tags deploy -e "app_repo_names=['Tester']"
# appc --tags deploy -e "app_repo_names=['Main']"
# appc --tags deploy -e "app_repo_names=['WebAppTest']" -e "@inventories/main/group_vars/azure/extra_vars_vault.yml"

- include_role:
    name: azure/resource_manager/deploy
    tasks_from: loop_app_environment
  loop: "{{app_repo_names}}"
  loop_control:
    loop_var: app_repo
  # when: app_repo_item.source == 'Azure'
  when: app_repo_item.az_resource_manager is defined
  tags: [azure, az, deploy, resource_manager, arm]
...