---
- name: Initialize Git in the project
  win_shell: "git init"
  args:
    chdir: "{{app_solution_dir}}"
    creates: "{{app_git_repo_dir}}"
  tags: [git, init]
  register: out_git_init

# https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore
- name: Ensure project has git-ignore
  win_copy:
    src: "{{app_gitignore | win_basename}}"
    dest: "{{app_gitignore}}"
    force: false # only when dest doesn't exist
  tags: [git, gitignore]

- name: Ensure project has git-attributes
  win_copy:
    src: "{{app_gitattributes | win_basename}}"
    dest: "{{app_gitattributes}}"
    force: false # only when dest doesn't exist
  tags: [git, gitattributes]

# https://elanderson.net/2016/09/add-git-ignore-to-existing-visual-studio-project/
# - name: Stop tracking files that should be ignored
#   win_shell: >-
#     git rm -r --cached .
#     git add .
#     git commit -am "Remove ignored files"
#   args:
#     chdir: "{{app_solution_dir}}"
#   register: out_git_untrack
#   tags: ["git", "rm"]
...