---
# ansible home -m include_role -a "name=windows/games/world_of_warcraft"
# ansible-playbook system_clean.yml --tags "world_of_warcraft"

- block:
  - name: Check for World of Warcraft screenshot directory
    win_stat:
      path: "{{version.value.screenshot_dir}}"
    loop: "{{versions}}"
    loop_control:
      loop_var: version
    register: out_stat_wow_ss

  - name: Backup World of Warcraft screenshots
    win_copy:
      remote_src: true
      src: "{{item.version.value.screenshot_dir}}"
      dest: "{{item.version.value.backup_dir}}"
    loop: "{{out_stat_wow_ss.results}}"
    when: item.stat.exists
    register: out_copy_wow_ss

  - name: Remove World of Warcraft screenshot directory
    win_file:
      path: "{{item.version.value.screenshot_dir}}"
      state: absent
    loop: "{{out_stat_wow_ss.results}}"
    when: item.stat.exists and out_copy_wow_ss is changed

  - name: Create World of Warcraft screenshot directory
    win_file:
      path: "{{item.version.value.screenshot_dir}}"
      state: directory
    loop: "{{out_stat_wow_ss.results}}"
    when: item.stat.exists and out_copy_wow_ss is changed


  - name: Backup World of Warcraft settings
    win_copy:
      remote_src: true
      src: "{{item.value.wtf_dir}}"
      dest: "{{item.value.backup_dir}}"
    loop: "{{versions}}"
    register: out_copy_wow_wtf


  - name: Backup World of Warcraft addons
    win_copy:
      remote_src: true
      src: "{{item.value.addon_dir}}"
      dest: "{{item.value.backup_dir}}"
    loop: "{{versions}}"
    register: out_copy_wow_addon


  # - name: Backup TradeSkillMaster settings

  vars:
    versions: "{{world_of_warcraft_backups | dict2items}}"
  tags: ["backup", "world_of_warcraft"]
...