---
# ansible home -m include_role -a "name=windows/games/world_of_warcraft"
# clean --tags wow


# Check if ss folder is empty prior to delete

- block:
  - name: Check for World of Warcraft screenshot directory
    win_stat:
      path: "{{version.value.screenshot_dir}}"
    loop: "{{world_of_warcraft_versions}}"
    loop_control:
      loop_var: version
    register: out_stat_wow_ss


  # - name: Remove World of Warcraft screenshot directory
  #   win_file:
  #     path: "{{item.version.value.screenshot_dir}}"
  #     state: absent
  #   loop: "{{out_stat_wow_ss.results}}"
  #   when: item.stat.exists and out_copy_wow_ss is changed

  # - name: Create World of Warcraft screenshot directory
  #   win_file:
  #     path: "{{item.version.value.screenshot_dir}}"
  #     state: directory
  #   loop: "{{out_stat_wow_ss.results}}"
  #   when: item.stat.exists and out_copy_wow_ss is changed


# Cleanup

  # - name: Cleanup World of Warcraft settings
  #   win_copy:
  #     remote_src: true
  #     src: "{{item.value.wtf_dir}}"
  #     dest: "{{item.value.archive_dir}}"
  #   loop: "{{world_of_warcraft_versions}}"
  #   register: out_copy_wow_wtf


  # - name: Cleanup World of Warcraft addons
  #   win_copy:
  #     remote_src: true
  #     src: "{{item.value.addon_dir}}"
  #     dest: "{{item.value.archive_dir}}"
  #   loop: "{{world_of_warcraft_versions}}"
  #   register: out_copy_wow_addon

  tags: ["world_of_warcraft", "wow", "cleanup"]
...