---
- block:
  - include_role:
      name: azure/service_plan/create
      tasks_from: create

  - debug:
      var: az_resource_group
  - debug:
      var: az_service_plan
  - debug:
      var: az_app_service
  - debug:
      var: az_service_plan_id

  # https://docs.ansible.com/ansible/latest/modules/azure_rm_webapp_module.html
  - name: Create a windows web app
    azure_rm_webapp:
      name: "{{az_app_service}}"
      resource_group: "{{az_resource_group}}"
      # plan: "{{az_service_plan}}"
      plan: "{{az_service_plan_id}}"
      state: present
  
  - fail:
      msg: break point
  
  tags: [azure, az, app_service, publish, host]
...