; --- Override values of main configuration ---
; https://github.com/Crypto137/MHServerEmu/blob/master/src/MHServerEmu/Config.ini
; /app/src/MHServerEmu/bin/x64/Release/net8.0/Config.ini

[Server]
Address=+
Port=8088
DataDirectory=/data

[WebFrontend]
; ; Listen on all interfaces, not just localhost
; Address=0.0.0.0
; Use '+' to listen on all interfaces for HttpListener on Linux
Address=+
; Use a non-conflicting port for the web dashboard
Port=8088

[SQLiteDBManager]
; Use the persistent /data volume for the database
FileName=/data/Account.db

[GroupingManager]
; Change the Message of the Day to confirm this file is being read
MotdText=THIS IS A TEST. CONFIG OVERRIDE IS WORKING.

[CustomGameOptions]
; Unlock all characters and team-ups automatically after the tutorial
AutoUnlockAvatars=true
AutoUnlockTeamUps=true
; Disables charge costs for movement powers to imitate pre-BUE behavior
DisableMovementPowerChargeCost = true
