---
- block:
  # https://docs.ansible.com/ansible/latest/modules/win_find_module.html
  - name: Find Desktop Shortcuts
    win_find:
      paths:
      - C:\Users\Public\Desktop
      - C:\Users\david\Desktop
      patterns: ["*.lnk"]
    register: find_result
    
  # https://docs.ansible.com/ansible/latest/modules/win_file_module.html
  - name: Delete Desktop Shortcuts
    win_file:
      path: "{{item.path}}"
      state: absent
    loop: "{{find_result.files}}"
    register: file_result
    
  - name: Display Remaining Files
    win_find:
      paths:
      - C:\Users\Public\Desktop
      - C:\Users\david\Desktop
    register: find_result
  
  tags: ["desktop"]
...