---
# ansible localhost -m include_role -a "name=azure/active_directory/create"


# active directory (1):(many) app subscriptions / app limited to 1 directory at a time
# Using Microsoft Identity platform (v2.0), not Azure Active Directory (v1.0) endpoints
# https://docs.microsoft.com/en-us/azure/active-directory/develop/azure-ad-endpoint-comparison
# --- Accounts in any Azure AD directory and personal Microsoft accounts - Multi-tenant
# https://docs.microsoft.com/en-us/azure/active-directory/develop/single-and-multi-tenant-apps
# https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp

# Install-Package Microsoft.Owin.Security.OpenIdConnect
# Install-Package Microsoft.Owin.Security.Cookies
# Install-Package Microsoft.Owin.Host.SystemWeb

- block:
  # https://docs.microsoft.com/en-us/cli/azure/ad/app#az-ad-app-create
  # NOTE: The az command itself is idempotent; provides same output as app list
  - name: Register an AD application
    command: >-
      az ad app create
      --display-name {{app_project}}
      --native-app
    no_log: true
    register: out_ad_app_create
    changed_when: not 'Found an existing application instance' in out_ad_app_create.stderr

  # https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade
  # - set_fact:
  #     az_ad_app_keys: "{{(out_ad_app_create.stdout | from_json).keys() | list | sort}}"
  # - set_fact:
  #     az_ad_app_convert: "{{out_ad_app_create.stdout | from_json | json_query('{appId: appId, displayName: displayName}')}}"
  - set_fact:
      az_ad_app_project_id: "{{out_ad_app_create.stdout | from_json | json_query('appId')}}"

  when: app_authentication != 'None'
  tags: ["azure", "az", "active_directory", "ad", "identity"]
...