---
# setup --tags desktop

- block:
  # https://docs.ansible.com/ansible/latest/modules/win_find_module.html
  - name: Find Desktop Shortcuts
    win_find:
      paths: "{{desktops}}"
      patterns: ["*.lnk"]
    no_log: true
    register: out_find_desktop
  
  # https://docs.ansible.com/ansible/latest/modules/win_file_module.html
  - name: Delete Desktop Shortcuts
    win_file:
      path: "{{item.path}}"
      state: absent
    loop: "{{out_find_desktop.files}}"
    register: file_result
    
  - name: Display Remaining Files
    win_find:
      paths: "{{desktops}}"
    register: out_find_desktop
  
  tags: [desktop]


# - block:
  # https://docs.ansible.com/ansible/latest/modules/win_mapped_drive_module.html
  # - H: \\HeroCamp\home
  # - O: \\HeroCamp\OneDrive
  # - M: \\HeroCamp\Multimedia
  # - P: \\HeroCamp\Public
  # - Z: \\HeroCamp\Pervy Yum Sauce

  # tags: [mount]
...