---
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# -------- Host Connection Settings --------
ansible_connection: winrm
# -------- WinRM Connection Settings --------
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
...