---
# https://docs.ansible.com/ansible/latest/modules/file_module.html
- name: Ensure Python module directory exists
  file:
    path: "{{python_user_site_dir}}"
    state: directory

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name: Deploy Python module
  copy:
    src: "{{item}}"
    dest: "{{python_user_site_dir}}/{{item}}"
  loop: "{{python_boilerplate_modules}}"

# - name: Install boilerplate package
#   copy:
#     src: /srv/myfiles/foo.conf
#     dest: /etc/foo.conf
#     mode: '0644'
...