---
# - debug:
#     var: app_project_names

# - debug:
#     var: app_project

# 'dotnet new' automatically performs restore
- name: Create .NET Core web app
  win_shell: >-
    dotnet new webapp
    --output {{app_project_dir}}
    --domain {{app_domain}}
    --org-read-access
    --auth {{app_authentication}}
  # --client-id {{hostvars['localhost']['az_ad_app_project_id']}}
  args:
    creates: "{{app_csproj}}"
  register: out_webapp_create
  # when:
  # - app_authentication == 'MultiOrg'
  # - hostvars['localhost']['az_ad_app_project_id']
  tags: [dotnet, new, webapp]

# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln
- name: Add project to the solution
  win_shell: "dotnet sln {{app_sln}} add {{app_csproj}}"
  register: out_sln_add
  changed_when: not 'already contains project' in out_sln_add.stdout
  tags: [dotnet, new, solution, sln, webapp]
...