---
# appc --tags repo -e "app_repo_names=['Tester']" --start-at-task="List all package references for project"
- block:
  - name: List all package references for project
    win_shell: "dotnet list {{app_project_dir}} package"
    register: out_dotnet_installed
    changed_when: false


  # - set_fact:
  #     dotnet_packages_installed: "{{out_dotnet_installed.stdout_lines[3:] | list | regex_replace('^   > (.*) .*$', '\\1')}}"
  #   tags: [dotnet, package, list]
  # - set_fact:
  #     dotnet_packages_to_install: "{{dotnet_packages | difference(out_dotnet_installed.stdout_lines)}}"
  #   tags: [dotnet, package, list]
  # - set_fact:
  #     dotnet_packages_to_uninstall: "{{dotnet_packages | intersect(out_dotnet_installed.stdout_lines)}}"
  #   tags: [dotnet, package, list]
  # - set_fact:
  #     dotnet_packages_filter_test: "{{out_dotnet_installed.stdout | from_package}}"
  #   tags: [dotnet, package, list]


  # - name: List all project-to-project references for project
  #   win_shell: "dotnet list {{app_project_dir}} reference"
  #   changed_when: false


  # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add
  # https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
  # https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
  - name: Install .NET Core package to project
    win_shell: "dotnet add package {{item}}"
    args:
      chdir: "{{app_project_dir}}"
    loop: "{{dotnet_packages}}"
    when: not item in out_dotnet_installed.stdout
  
  tags: [dotnet, new, package]
...