---
- block:
  - debug:
      msg: "App .NET project: {{app_project_item.name}}"

  # - debug:
  #     var: app_project_item


  # https://docs.microsoft.com/en-us/cli/azure/ad/signed-in-user
  - name: Verify Azure login
    win_shell: "az ad signed-in-user show"
    when: app_authentication != 'None'
    register: out_az_ad_user
    changed_when: false # query only
    failed_when: out_az_ad_user.rc != 0
    no_log: true


  # 'dotnet new' automatically calls build and restore
  # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
  - name: Create .NET Core project
    win_shell: >-
      dotnet new {{app_project_item.template}}
      --output {{app_project_dir}}
      --domain {{app_domain}}
      --org-read-access
      --auth {{app_authentication}}
      --framework {{app_project_item.framework | default('netcoreapp3.1')}}
    # --client-id {{hostvars['localhost']['az_ad_app_client_id']}}
    args:
      creates: "{{app_csproj}}"
    tags: [new, webapp]
    register: out_webapp_create


  # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln
  - name: Add project to the solution
    win_shell: "dotnet sln {{app_sln}} add {{app_csproj}}"
    tags: [new, solution, sln, webapp]
    register: out_sln_add
    changed_when: not 'already contains project' in out_sln_add.stdout


  - include_role:
      name: windows/apps/git/init
    tags: [git]
  

  - include_role:
      name: windows/apps/dotnet/create
      tasks_from: package
    tags: [add, package]


  # - fail:
  #     msg: break point

  # # https://docs.ansible.com/ansible/latest/modules/pause_module.html
  # - pause:

  # - include_role:
  #     name: windows/apps/dotnet/create
  #     tasks_from: ef
  #   tags: [entity_framework, ef]

  tags: [repository, repo, dotnet]
...