# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core

trigger:
- master

stages:
- stage: Build
  pool:
    vmImage: "ubuntu-latest"
  variables:
    dotnetRuntimeVersion: "3.1.x"
    solution: "**/*.sln"
    buildPlatform: "AnyCPU"
    buildConfiguration: "Release"
    scriptName: "migrations.sql"
    dbContext: "DefaultContext"
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: "Install .NET Core SDK"
      inputs:
        version: "$(dotnetRuntimeVersion)"
        packageType: runtime
    
    # Omit '--version' here and let SDK find correct EF package
    - script: dotnet tool install --global dotnet-ef
      displayName: "Install .NET EF Core"

    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    - task: NuGetCommand@2
      displayName: "Restore NuGet package dependencies"
      inputs:
        restoreSolution: "$(solution)"

    - task: DotNetCoreCLI@2
      displayName: "Build .NET: $(buildConfiguration)"
      inputs:
        command: "build"
        arguments: "--configuration $(buildConfiguration)"

    # Build Restored /home/vsts/work/1/s/Test-PipelineArmTemplates.Web/Test-PipelineArmTemplates.Web.csproj (in 152 ms).
    # Test-PipelineArmTemplates.Web -> /home/vsts/work/1/s/Test-PipelineArmTemplates.Web/bin/Release/netcoreapp3.1/Test-PipelineArmTemplates.Web.dll
    # Test-PipelineArmTemplates.Web -> /home/vsts/work/1/s/Test-PipelineArmTemplates.Web/bin/Release/netcoreapp3.1/Test-PipelineArmTemplates.Web.Views.dll


  
    - script: echo This is pipeline $(System.DefinitionId)      # 8
    - bash: pwd                                                 # /home/vsts/work/1/s       # same as $(System.DefaultWorkingDirectory)
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
    - bash: "ls -la $(Agent.BuildDirectory)"                    # /home/vsts/work/1         # returned TestResults, a, b, s
    - bash: "ls -la $(Build.ArtifactStagingDirectory)"          # /home/vsts/work/1/a
    - bash: "ls -la $(Build.SourcesDirectory)"                  # /home/vsts/work/1/s
    


    # - script: >-
    #     dotnet ef migrations script
    #     --startup-project $(Build.SourcesDirectory)
    #     --context $(dbContext)
    #     --configuration $(buildConfiguration)
    #     --output $(Build.ArtifactStagingDirectory)/sql/$(scriptName)
    #     --idempotent
      
    # https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
    - script: >-
        dotnet ef migrations script
        --project ContosoUniversity/ContosoUniversity.csproj
        --startup-project ContosoUniversity/ContosoUniversity.csproj
        --output $(Build.ArtifactStagingDirectory)/sql/$(scriptName)
        --idempotent
      # --runtime version: "$(dotnetRuntimeVersion)"
      displayName: "Generate SQL migration script"
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line
      # workingDirectory: "$(Agent.BuildDirectory)/s/Test-PipelineArmTemplates.Web/bin/Release/netcoreapp3.1"
      # workingDirectory: "$(Build.SourcesDirectory)/Test-PipelineArmTemplates.Web"
      # workingDirectory: "$(Build.SourcesDirectory)/Test-PipelineArmTemplates.Web"
      # *ERROR: Test-PipelineArmTemplates.Web must reference 'Microsoft.EntityFrameworkCore.Design' package

      
    - bash: "ls -la $(Agent.BuildDirectory)"                    # /home/vsts/work/1         # returned TestResults, a, b, s
    - bash: "ls -la $(Build.ArtifactStagingDirectory)"          # /home/vsts/work/1/a
    - bash: "ls -la $(Build.SourcesDirectory)"                  # /home/vsts/work/1/s


    - task: DotNetCoreCLI@2
      displayName: "dotnet test $(buildConfiguration)"
      inputs:
        command: test
        projects: "**/*Tests/*.csproj"
        arguments: "--configuration $(buildConfiguration)"

    # Provides zip file for web app service
    - task: DotNetCoreCLI@2
      displayName: "Stage build output"
      inputs:
        command: publish
        publishWebProjects: True
        arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
        zipAfterPublish: True

    # Provides dacpac file for database
    - task: CopyFiles@2
      displayName: "Copy files to: $(Build.ArtifactStagingDirectory)"
      inputs:
        sourceFolder: "$(Build.SourcesDirectory)"
        contents: "**\\bin\\$(buildConfiguration)\\**"
        targetFolder: "$(Build.ArtifactStagingDirectory)"

    - task: PublishBuildArtifacts@1
      displayName: "Publish build artifact: drop"
      inputs:
        pathtoPublish: "$(Build.ArtifactStagingDirectory)" 
        artifactName: "drop"

  
    - bash: "ls -la $(Agent.BuildDirectory)"                    # /home/vsts/work/1         # returned TestResults, a, b, s
    - bash: "ls -la $(Build.ArtifactStagingDirectory)"          # /home/vsts/work/1/a
    - bash: "ls -la $(Build.SourcesDirectory)"                  # /home/vsts/work/1/s
