---
- include_role:
    name: azure/resource_group/create

# https://docs.ansible.com/ansible/latest/modules/azure_rm_sqlserver_module.html
- name: Create SQL server
  azure_rm_sqlserver:
    name: "{{az_sql_server}}"
    resource_group: "{{az_resource_group}}"
    admin_username: "{{db_username}}"
    admin_password: "{{db_password}}"
...