---
# https://code.visualstudio.com/docs
# https://stackoverflow.com/questions/42606837/how-do-i-use-bash-on-windows-from-the-visual-studio-code-integrated-terminal


# ---------------------------------------------------------
# ---------------------------------------------------------
# https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management
# TODO: Instead of what's below (which worked!), do this command line version of 'code --install-extension'
#   for Windows and Linux vscode separately
- name: Install VSCode Extensions
  win_command: "code --install-extension {{item}}"
  loop: "{{vscode_extensions}}"
# ---------------------------------------------------------
# ---------------------------------------------------------
# ansible windows -m include_role -a 'name=windows/vscode/setup'


# Taken from /home/rhodair/pc-setup/ansible_playbooks/roles/windows/backup/apps/vscode/tasks/main.yml
# https://docs.ansible.com/ansible/latest/modules/win_file_module.html
# - name: Ensure backup directory exists
#   win_file:
#     path: D:\OneDrive\Backups\vscode-extensions
#     state: directory
# https://docs.ansible.com/ansible/latest/modules/win_copy_module.html
# - name: Backup VSCode Extensions
#   win_copy:
#     # src: %USERPROFILE%\.vscode\extensions
#     src: C:\Users\david\.vscode\extensions
#     dest: D:\OneDrive\Backups\vscode-extensions
#     remote_src: yes


# - name: Configure VSCode settings
#   - move json settings files for user and workspace
...