---
# appc -e "app_repo_names=['Tester']" --tags ad

# https://simonagren.github.io/azcli-adscope/
# https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/assign-user-or-group-access-portal
- block:
  # Dependency for 'az_ad_sp_service_providers'
  - include_role:
      name: azure/active_directory/service_principal/fetch
    run_once: true
  
  # Dependency for 'az_ad_app_client_id'
  - include_role:
      name: azure/active_directory/application/show
  
  # https://docs.microsoft.com/en-us/cli/azure/ad/app/permission
  - name: List Azure AD application's active permissions
    command: >-
      az ad app permission list
      --id {{az_ad_app_service_principal_id}}
    # --id {{az_ad_app_client_id}}
    register: az_ad_app_permission_list_facts
    changed_when: false # query only
    failed_when: false  # query only
    ignore_errors: true
    # no_log: true

  - debug:
      var: az_ad_app_permission_active_ids
  - debug:
      var: az_ad_app_permission_expected_ids
  - debug:
      var: az_ad_app_permission_missing_ids


  # Ignore stderr warning: Invoking 'az ad app permission grant' is needed to make the change effective
  - name: Add Azure AD application's missing permissions
    command: >-
      az ad app permission add
      --id {{az_ad_app_service_principal_id}}
      --api {{az_ad_sp_service_providers['Microsoft Graph']}}
      --api-permissions {{item}}=Scope
    # --id {{az_ad_app_client_id}}
    loop: "{{az_ad_app_permission_missing_ids}}"
    register: az_ad_app_permission_add_facts
    changed_when: false # query only
    failed_when: false  # query only
    ignore_errors: true
    # no_log: true

  tags: [azure, az, active_directory, ad, application, identity]
...