---
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
# https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
# List available templates: dotnet new -l
- name: Create a Razor Pages web app
  win_shell: >-
    dotnet new webapp
    --output {{app_location}}\\{{app_project}}
    --name {{app_project}}
    --auth {{app_authentication | default('None')}}
    --client-id {{hostvars['localhost']['az_ad_app_project_id']}}
  #   --org-read-access
  #   --domain {{az_ad_domain}}
  # --dry-run
  args:
    creates: "{{app_location}}\\{{app_project}}"
  register: out_webapp_create
  when: hostvars['localhost']['az_ad_app_project_id']

- block:
  - name: Install EFCore database provider
    win_shell: "dotnet add package Microsoft.EntityFrameworkCore.Sqlite"
    # args:
    #   chdir: "{{app_location}}\\{{app_project}}"

  # - name: Add EFCore design package
  #   win_shell: "dotnet add package Microsoft.EntityFrameworkCore.Design"

  # - name: Create initial database migration
  #   win_shell: "dotnet ef migrations add {{migration_message|default('Initial')}}"
  
  # --- Fresh app migrations already up-to-date; TODO: turn this into alias
  # - name: Update database with latest migrations
  #   win_shell: "dotnet ef database update"
  #   args:
  #     chdir: "{{app_location}}\\{{app_project}}"
  #   register: out_database_update

  - name: Install code generator (scaffold)
    win_shell: "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design"

  - name: Build the web app
    win_shell: "dotnet build"

  args:
    chdir: "{{app_location}}\\{{app_project}}"
  when: out_webapp_create is changed
  tags: ["database", "db", "identity"]




# - name: List all package references of the project
#   win_shell: "dotnet list {{app_location}} package"
#   changed_when: false

# - name: List all project-to-project references of the project
#   win_shell: "dotnet list {{app_location}} reference"
#   changed_when: false


# --- Don't run app from command line; stick to Visual Studio ---
# # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run
# - name: Run the web application
#   win_shell: >-
#     dotnet run
#     --project {{app_location}}
#     --launch-profile Development
...