---
# ansible windows -m include_role -a name="windows/apps/dotnet/new"

# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new
# https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
- name: Create .NET Core solution
  win_shell: "dotnet new sln --output {{app_solution_dir}}"
  args:
    creates: "{{app_solution_dir}}"
  register: out_webapp_create
  tags: [solution, sln]

# 'dotnet new' automatically performs restore
- name: Create .NET Core web app
  win_shell: >-
    dotnet new webapp
    --output {{app_project_dir}}
    --domain {{app_domain}}
    --org-read-access
    --auth {{app_authentication | default('None')}}
  # --client-id {{hostvars['localhost']['az_ad_app_project_id']}}
  args:
    creates: "{{app_project_dir}}"
  register: out_webapp_create
  # when:
  # - app_authentication == 'MultiOrg'
  # - hostvars['localhost']['az_ad_app_project_id']
  tags: [webapp]

# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln
- name: Add project to the solution
  win_shell: "dotnet sln {{app_sln}} add {{app_csproj}}"
  register: out_sln_add
  changed_when: not 'already contains project' in out_sln_add.stdout
  tags: [solution, sln, webapp]


- block:
  # https://docs.ansible.com/ansible/latest/modules/win_copy_module.html
  - name: Ensure solution has readme
    win_copy:
      src: "{{app_readme | win_basename}}"
      dest: "{{app_readme}}"
    register: out_copy_readme
    tags: [readme]

  - name: Ensure solution has license
    win_copy:
      src: "{{app_license | win_basename}}"
      dest: "{{app_license}}"
    register: out_copy_license
    tags: [license]

  when: app_use_extras
  tags: [extras]
...