---
desktops:
- C:\Users\Public\Desktop
- C:\Users\david\Desktop


file_naming_convention:
  onedrive:
  - _DMR:
    - Audio
    - Development
    - Documents
    - Friends
      - Ashee
      - Ben
      - Philip
    - Pictures
    - Videogames
    - Videos
      - Anime
      - Programming
      - Science
      - Superheroes
    - Writings

  nas:
  - Container           # QNAP Container Station data
  - Download
  - home                # user home (admin)
  - homes               # admin and Public homes
  - Multimedia          # Plex source data
  - OneDrive            # system update sync
  - Pervy Yum Sauce
  - Public              # empty
  - Web                 # empty

  plex: null


# ------------------------ Scheduled Tasks ------------------------
# https://docs.microsoft.com/en-us/windows/win32/taskschd/trigger-types
# types: boot, logon, daily, weekly, monthly, monthlydow, time
# start_boundary required when type is daily, weekly, monthly, monthlydow, time
# triggers.days_of_month required when type is monthly
# triggers.days_of_week required when type is weekly, monthlydow (optional)
scheduled_tasks:
- name: AutoHotkey World of Warcraft
  actions:
  # - path: D:\OneDrive\Documents\WorldOfWarcraft_SpamButton.ahk
  - path: C:\Program Files\AutoHotkey\AutoHotkey.exe
    arguments: D:\OneDrive\Documents\WorldOfWarcraft_SpamButton.ahk
  triggers:
  - type: boot

# - name: Ansible Daily Setup
#   description: "Ansible playbook that installs, updates, and provisions Windows 10 + WSL"
#   actions:
#   - path: C:\Windows\System32\bash.exe
#     arguments: -c ansible-playbook system_setup.yml
#     working_directory: ~/pc-setup/ansible_playbooks
#   triggers:
#   - type: daily
#     start_boundary: "2020-01-01T06:00:00-06:00"
#   - type: boot

# https://dev.to/ironfroggy/wsl-tips-starting-linux-background-services-on-windows-login-3o98
- name: Ansible Daily Backup
  description: Ansible playbook to back up app & game files
  actions:
  - path: C:\Windows\System32\bash.exe
    arguments: -c ansible-playbook system_setup.yml
    working_directory: ~/pc-setup/ansible_playbooks
  triggers:
  - type: daily
    start_boundary: "2020-01-01T04:00:00-06:00"
...