---
desktops:
- C:\Users\Public\Desktop
- C:\Users\david\Desktop


file_naming_convention:
  onedrive:
  - _DMR:
    - Audio
    - Development
    - Documents
    - Friends
      - Ashee
      - Ben
      - Philip
    - Pictures
    - Videogames
    - Videos
      - Anime
      - Programming
      - Science
      - Superheroes
    - Writings

  nas:
  - Container           # QNAP Container Station data
  - Download
  - home                # user home (admin)
  - homes               # admin and Public homes
  - Multimedia          # Plex source data
  - OneDrive            # system update sync
  - Pervy Yum Sauce
  - Public              # empty
  - Web                 # empty

  plex: null
...