---
# --- Microsoft Visual Studio 2019 ---
# https://chocolatey.org/packages/visualstudio2019community
# https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
# https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community
# TODO: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpenCommandLine
# --- Microsoft Office 365 ---
# https://chocolatey.org/packages/microsoft-office-deployment

powershell_uninstall_appx_packages:
  - CanonicalGroupLimited.Ubuntu18.04onWindows

# https://chocolatey.org/packages/*
chocolatey_packages:
  install:
    # --- Productivity ---
    - name: GoogleChrome
    - name: 7zip
    - name: ccleaner
    - name: nordvpn
    # - name: microsoft-office-deployment
    #   pseudo_name: Office365HomePremium
    #   package_params: >-
    #     /64bit
    #     /Product O365HomePremRetail
    #     /Exclude Publisher,Lync,Groove
    - name: qbittorrent
    - name: speccy
    # - name: recuva
    # - name: defraggler

    # --- Development ---
    - name: powershell-core
    - name: oh-my-posh
    - name: git
    - name: github-desktop
    - name: vscode
    # - name: visualstudio2022community
    #   package_params: >-
    #     --locale en-US
    #     --add Microsoft.VisualStudio.Workload.NetWeb;includeRecommended
    #     --add Microsoft.VisualStudio.Workload.Azure;includeRecommended
    #     --quiet
    - name: python3
    - name: dotnetcore-sdk
    - name: nodejs-lts
    - name: azure-cli
    - name: mongodb
    - name: mongodb-compass
    - name: mongodb-shell
    - name: postman
    - name: terraform

    # --- Media ---
    - name: geforce-experience
    - name: adobereader
    - name: AdobeAIR
    - name: adobeshockwaveplayer
    - name: spotify
    - name: comicrack
    # - name: blender

    # --- Video Editing ---
    - name: mkvtoolnix # https://mkvtoolnix.download/doc/mkvmerge.html
    - name: MakeMKV
    - name: handbrake
    - name: k-litecodecpackfull
    - name: 4k-video-downloader
    # - name: jubler
    # - name: chatterino

    # --- Videogames ---
    - name: directx
    - name: steam
    - name: discord

  uninstall:
    - name: python2
    - name: mitkerberos
    # - name: docker-desktop
    # - name: unity
    # - name: obs-studio
    # - name: gimp
    - name: vlc
    - name: passkey
    - name: typescript
    - name: sass
    - name: dart-sdk # sass dependency
    # - name: jekyll
    # - name: microsoftazurestorageexplorer
    # - name: streamlabs-obs
    # - name: twitch

pip_packages:
  - pip
  - pytz
  - colorlog

vscode_extensions:
  # --- Baseline ---
  - bierner.markdown-preview-github-styles
  - bowlerhatllc.vscode-as3mxml # ActionScript
  - christian-kohler.path-intellisense
  - DavidAnson.vscode-markdownlint
  - esbenp.prettier-vscode
  - mikestead.dotenv
  - mongodb.mongodb-vscode
  - natqe.reload
  - redhat.vscode-yaml
  # - rog2.luacheck
  # - tangzx.emmylua
  - theumletteam.umlet # UML Diagrams
  - vscode-icons-team.vscode-icons
  - wayou.vscode-todo-highlight

  # --- DevOps ---
  - donjayamanne.githistory
  - hashicorp.terraform
  - ms-vscode.azure-account
  - ms-azure-devops.azure-pipelines
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode.powershell
  - msazurermtools.azurerm-vscode-tools

  # --- HTML, CSS/SASS, JavaScript/TypeScript ---
  - ms-vscode.vscode-typescript-tslint-plugin
  - dbaeumer.vscode-eslint
  # - DigitalBrainstem.javascript-ejs-support
  - formulahendry.auto-close-tag
  - formulahendry.auto-rename-tag
  - rbbit.typescript-hero
  - sibiraj-s.vscode-scss-formatter
  - steoates.autoimport
  - syler.sass-indented
  - sz-p.dependencygraph
  - WooodHead.disable-eslint-rule
  # - xabikos.JavaScriptSnippets

  # --- Angular ---
  - Angular.ng-template

  # --- Vue ---
  - MisterJ.vue-volar-extention-pack
  # - Vue.volar
  - Wscats.vue

  # --- C# .NET ---
  - ms-vscode.csharp
  - ms-dotnettools.csharp
  - ms-dotnettools.vscode-dotnet-runtime

  # --- Node.js ---
  - 42Crunch.vscode-openapi
  - christian-kohler.npm-intellisense
  - howardzuo.vscode-npm-dependency

  # --- Python ---
  - ms-python.pylint
  - ms-python.python
  - ms-python.vscode-pylance
