---
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add
# https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
# https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
- name: Install SQLite database provider
  win_shell: "dotnet add package {{item}}"
  args:
    chdir: "{{app_project_dir}}"
  loop: "{{app_database_packages}}"
  when:
  - app_use_database
  # - out_webapp_create is changed
  tags: ["dotnet", "package", "database", "db"]


# - name: Create initial database migration
#   win_shell: "dotnet ef migrations add {{migration_message|default('Initial')}}"

# --- Fresh app migrations already up-to-date; TODO: turn this into alias
# - name: Update database with latest migrations
#   win_shell: "dotnet ef database update"
#   args:
#     chdir: "{{app_project_dir}}"
#   register: out_database_update

- name: Install code generator (scaffold)
  win_shell: "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design"
  args:
    chdir: "{{app_project_dir}}"
  when: out_webapp_create is changed
  tags: ["dotnet", "package", "scaffold", "database", "identity"]


# - name: List all package references of the project
#   win_shell: "dotnet list {{app_project_dir}} package"
#   changed_when: false

# - name: List all project-to-project references of the project
#   win_shell: "dotnet list {{app_project_dir}} reference"
#   changed_when: false


# https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/invoke-item
# - name: Open the web app in Visual Studio
#   win_shell: "Invoke-Item -Path {{app_csproj}}"
#   tags: ["visual_studio", "vs"]

# - name: Build the web app
#   win_shell: "dotnet build {{app_project_dir}}"
#   tags: ["dotnet", "build"]

# --- Don't run app from command line; stick to Visual Studio ---
# # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run
# - name: Run the web application
#   win_shell: >-
#     dotnet run
#     --project {{app_location_dir}}
#     --launch-profile Development
...