---
- name: List all package references of the project
  win_shell: "dotnet list {{app_project_dir}} package"
  changed_when: false

# - name: List all project-to-project references of the project
#   win_shell: "dotnet list {{app_project_dir}} reference"
#   changed_when: false


# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add
# https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
# https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
- name: Install SQLite database provider
  win_shell: "dotnet add package {{item}}"
  args:
    chdir: "{{app_project_dir}}"
  loop: "{{app_development_packages | union(app_database_packages)}}"
  # when: app_use_database
  when: false
  tags: ["dotnet", "package", "database", "db"]
...